"""Add parameter parse_pois_from_osm

Revision ID: 795308e6d7c
Revises: 53c1e84535f8
Create Date: 2015-03-03 10:50:58.000922

"""

# revision identifiers, used by Alembic.
revision = '795308e6d7c'
down_revision = '53c1e84535f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parameters', sa.Column('parse_pois_from_osm', sa.BOOLEAN(), nullable=True), schema='navitia')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parameters', 'parse_pois_from_osm', schema='navitia')
    ### end Alembic commands ###
