# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/navitia/navitia/source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/navitia/navitia

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/navitia/navitia/CMakeFiles /home/runner/work/navitia/navitia/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/navitia/navitia/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named config

# Build rule for target.
config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 config
.PHONY : config

# fast build rule for target.
config/fast:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/build
.PHONY : config/fast

#=============================================================================
# Target rules for targets named tidy_fix

# Build rule for target.
tidy_fix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tidy_fix
.PHONY : tidy_fix

# fast build rule for target.
tidy_fix/fast:
	$(MAKE) -f CMakeFiles/tidy_fix.dir/build.make CMakeFiles/tidy_fix.dir/build
.PHONY : tidy_fix/fast

#=============================================================================
# Target rules for targets named docker_test

# Build rule for target.
docker_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 docker_test
.PHONY : docker_test

# fast build rule for target.
docker_test/fast:
	$(MAKE) -f CMakeFiles/docker_test.dir/build.make CMakeFiles/docker_test.dir/build
.PHONY : docker_test/fast

#=============================================================================
# Target rules for targets named tidy

# Build rule for target.
tidy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tidy
.PHONY : tidy

# fast build rule for target.
tidy/fast:
	$(MAKE) -f CMakeFiles/tidy.dir/build.make CMakeFiles/tidy.dir/build
.PHONY : tidy/fast

#=============================================================================
# Target rules for targets named rabbitmq-static

# Build rule for target.
rabbitmq-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rabbitmq-static
.PHONY : rabbitmq-static

# fast build rule for target.
rabbitmq-static/fast:
	$(MAKE) -f third_party/librabbitmq-c/librabbitmq/CMakeFiles/rabbitmq-static.dir/build.make third_party/librabbitmq-c/librabbitmq/CMakeFiles/rabbitmq-static.dir/build
.PHONY : rabbitmq-static/fast

#=============================================================================
# Target rules for targets named SimpleAmqpClient

# Build rule for target.
SimpleAmqpClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SimpleAmqpClient
.PHONY : SimpleAmqpClient

# fast build rule for target.
SimpleAmqpClient/fast:
	$(MAKE) -f third_party/SimpleAmqpClient/CMakeFiles/SimpleAmqpClient.dir/build.make third_party/SimpleAmqpClient/CMakeFiles/SimpleAmqpClient.dir/build
.PHONY : SimpleAmqpClient/fast

#=============================================================================
# Target rules for targets named prometheus-cpp-core

# Build rule for target.
prometheus-cpp-core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prometheus-cpp-core
.PHONY : prometheus-cpp-core

# fast build rule for target.
prometheus-cpp-core/fast:
	$(MAKE) -f third_party/prometheus-cpp/core/CMakeFiles/prometheus-cpp-core.dir/build.make third_party/prometheus-cpp/core/CMakeFiles/prometheus-cpp-core.dir/build
.PHONY : prometheus-cpp-core/fast

#=============================================================================
# Target rules for targets named civetweb

# Build rule for target.
civetweb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 civetweb
.PHONY : civetweb

# fast build rule for target.
civetweb/fast:
	$(MAKE) -f third_party/prometheus-cpp/pull/CMakeFiles/civetweb.dir/build.make third_party/prometheus-cpp/pull/CMakeFiles/civetweb.dir/build
.PHONY : civetweb/fast

#=============================================================================
# Target rules for targets named prometheus-cpp-pull

# Build rule for target.
prometheus-cpp-pull: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prometheus-cpp-pull
.PHONY : prometheus-cpp-pull

# fast build rule for target.
prometheus-cpp-pull/fast:
	$(MAKE) -f third_party/prometheus-cpp/pull/CMakeFiles/prometheus-cpp-pull.dir/build.make third_party/prometheus-cpp/pull/CMakeFiles/prometheus-cpp-pull.dir/build
.PHONY : prometheus-cpp-pull/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f utils/CMakeFiles/utils.dir/build.make utils/CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named idx_map_test

# Build rule for target.
idx_map_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idx_map_test
.PHONY : idx_map_test

# fast build rule for target.
idx_map_test/fast:
	$(MAKE) -f utils/tests/CMakeFiles/idx_map_test.dir/build.make utils/tests/CMakeFiles/idx_map_test.dir/build
.PHONY : idx_map_test/fast

#=============================================================================
# Target rules for targets named multi_obj_pool_test

# Build rule for target.
multi_obj_pool_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multi_obj_pool_test
.PHONY : multi_obj_pool_test

# fast build rule for target.
multi_obj_pool_test/fast:
	$(MAKE) -f utils/tests/CMakeFiles/multi_obj_pool_test.dir/build.make utils/tests/CMakeFiles/multi_obj_pool_test.dir/build
.PHONY : multi_obj_pool_test/fast

#=============================================================================
# Target rules for targets named utils_test

# Build rule for target.
utils_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils_test
.PHONY : utils_test

# fast build rule for target.
utils_test/fast:
	$(MAKE) -f utils/tests/CMakeFiles/utils_test.dir/build.make utils/tests/CMakeFiles/utils_test.dir/build
.PHONY : utils_test/fast

#=============================================================================
# Target rules for targets named obj_factory_test

# Build rule for target.
obj_factory_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obj_factory_test
.PHONY : obj_factory_test

# fast build rule for target.
obj_factory_test/fast:
	$(MAKE) -f utils/tests/CMakeFiles/obj_factory_test.dir/build.make utils/tests/CMakeFiles/obj_factory_test.dir/build
.PHONY : obj_factory_test/fast

#=============================================================================
# Target rules for targets named lru_test

# Build rule for target.
lru_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lru_test
.PHONY : lru_test

# fast build rule for target.
lru_test/fast:
	$(MAKE) -f utils/tests/CMakeFiles/lru_test.dir/build.make utils/tests/CMakeFiles/lru_test.dir/build
.PHONY : lru_test/fast

#=============================================================================
# Target rules for targets named map_find_test

# Build rule for target.
map_find_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 map_find_test
.PHONY : map_find_test

# fast build rule for target.
map_find_test/fast:
	$(MAKE) -f utils/tests/CMakeFiles/map_find_test.dir/build.make utils/tests/CMakeFiles/map_find_test.dir/build
.PHONY : map_find_test/fast

#=============================================================================
# Target rules for targets named deadline_test

# Build rule for target.
deadline_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deadline_test
.PHONY : deadline_test

# fast build rule for target.
deadline_test/fast:
	$(MAKE) -f utils/tests/CMakeFiles/deadline_test.dir/build.make utils/tests/CMakeFiles/deadline_test.dir/build
.PHONY : deadline_test/fast

#=============================================================================
# Target rules for targets named csvreader_test

# Build rule for target.
csvreader_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csvreader_test
.PHONY : csvreader_test

# fast build rule for target.
csvreader_test/fast:
	$(MAKE) -f utils/tests/CMakeFiles/csvreader_test.dir/build.make utils/tests/CMakeFiles/csvreader_test.dir/build
.PHONY : csvreader_test/fast

#=============================================================================
# Target rules for targets named functions_test

# Build rule for target.
functions_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 functions_test
.PHONY : functions_test

# fast build rule for target.
functions_test/fast:
	$(MAKE) -f utils/tests/CMakeFiles/functions_test.dir/build.make utils/tests/CMakeFiles/functions_test.dir/build
.PHONY : functions_test/fast

#=============================================================================
# Target rules for targets named data

# Build rule for target.
data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 data
.PHONY : data

# fast build rule for target.
data/fast:
	$(MAKE) -f type/CMakeFiles/data.dir/build.make type/CMakeFiles/data.dir/build
.PHONY : data/fast

#=============================================================================
# Target rules for targets named protobuf_files

# Build rule for target.
protobuf_files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protobuf_files
.PHONY : protobuf_files

# fast build rule for target.
protobuf_files/fast:
	$(MAKE) -f type/CMakeFiles/protobuf_files.dir/build.make type/CMakeFiles/protobuf_files.dir/build
.PHONY : protobuf_files/fast

#=============================================================================
# Target rules for targets named pb_lib

# Build rule for target.
pb_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pb_lib
.PHONY : pb_lib

# fast build rule for target.
pb_lib/fast:
	$(MAKE) -f type/CMakeFiles/pb_lib.dir/build.make type/CMakeFiles/pb_lib.dir/build
.PHONY : pb_lib/fast

#=============================================================================
# Target rules for targets named types

# Build rule for target.
types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 types
.PHONY : types

# fast build rule for target.
types/fast:
	$(MAKE) -f type/CMakeFiles/types.dir/build.make type/CMakeFiles/types.dir/build
.PHONY : types/fast

#=============================================================================
# Target rules for targets named pb_converter

# Build rule for target.
pb_converter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pb_converter
.PHONY : pb_converter

# fast build rule for target.
pb_converter/fast:
	$(MAKE) -f type/CMakeFiles/pb_converter.dir/build.make type/CMakeFiles/pb_converter.dir/build
.PHONY : pb_converter/fast

#=============================================================================
# Target rules for targets named accessible_test

# Build rule for target.
accessible_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 accessible_test
.PHONY : accessible_test

# fast build rule for target.
accessible_test/fast:
	$(MAKE) -f type/tests/CMakeFiles/accessible_test.dir/build.make type/tests/CMakeFiles/accessible_test.dir/build
.PHONY : accessible_test/fast

#=============================================================================
# Target rules for targets named fill_pb_placemark_test

# Build rule for target.
fill_pb_placemark_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fill_pb_placemark_test
.PHONY : fill_pb_placemark_test

# fast build rule for target.
fill_pb_placemark_test/fast:
	$(MAKE) -f type/tests/CMakeFiles/fill_pb_placemark_test.dir/build.make type/tests/CMakeFiles/fill_pb_placemark_test.dir/build
.PHONY : fill_pb_placemark_test/fast

#=============================================================================
# Target rules for targets named datetime_test

# Build rule for target.
datetime_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 datetime_test
.PHONY : datetime_test

# fast build rule for target.
datetime_test/fast:
	$(MAKE) -f type/tests/CMakeFiles/datetime_test.dir/build.make type/tests/CMakeFiles/datetime_test.dir/build
.PHONY : datetime_test/fast

#=============================================================================
# Target rules for targets named headsign_test

# Build rule for target.
headsign_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 headsign_test
.PHONY : headsign_test

# fast build rule for target.
headsign_test/fast:
	$(MAKE) -f type/tests/CMakeFiles/headsign_test.dir/build.make type/tests/CMakeFiles/headsign_test.dir/build
.PHONY : headsign_test/fast

#=============================================================================
# Target rules for targets named multi_polygon_map_test

# Build rule for target.
multi_polygon_map_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multi_polygon_map_test
.PHONY : multi_polygon_map_test

# fast build rule for target.
multi_polygon_map_test/fast:
	$(MAKE) -f type/tests/CMakeFiles/multi_polygon_map_test.dir/build.make type/tests/CMakeFiles/multi_polygon_map_test.dir/build
.PHONY : multi_polygon_map_test/fast

#=============================================================================
# Target rules for targets named aggregation_odt_test

# Build rule for target.
aggregation_odt_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aggregation_odt_test
.PHONY : aggregation_odt_test

# fast build rule for target.
aggregation_odt_test/fast:
	$(MAKE) -f type/tests/CMakeFiles/aggregation_odt_test.dir/build.make type/tests/CMakeFiles/aggregation_odt_test.dir/build
.PHONY : aggregation_odt_test/fast

#=============================================================================
# Target rules for targets named fill_pb_object_tests

# Build rule for target.
fill_pb_object_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fill_pb_object_tests
.PHONY : fill_pb_object_tests

# fast build rule for target.
fill_pb_object_tests/fast:
	$(MAKE) -f type/tests/CMakeFiles/fill_pb_object_tests.dir/build.make type/tests/CMakeFiles/fill_pb_object_tests.dir/build
.PHONY : fill_pb_object_tests/fast

#=============================================================================
# Target rules for targets named create_vj_test

# Build rule for target.
create_vj_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 create_vj_test
.PHONY : create_vj_test

# fast build rule for target.
create_vj_test/fast:
	$(MAKE) -f type/tests/CMakeFiles/create_vj_test.dir/build.make type/tests/CMakeFiles/create_vj_test.dir/build
.PHONY : create_vj_test/fast

#=============================================================================
# Target rules for targets named comments_test

# Build rule for target.
comments_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 comments_test
.PHONY : comments_test

# fast build rule for target.
comments_test/fast:
	$(MAKE) -f type/tests/CMakeFiles/comments_test.dir/build.make type/tests/CMakeFiles/comments_test.dir/build
.PHONY : comments_test/fast

#=============================================================================
# Target rules for targets named data_test

# Build rule for target.
data_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 data_test
.PHONY : data_test

# fast build rule for target.
data_test/fast:
	$(MAKE) -f type/tests/CMakeFiles/data_test.dir/build.make type/tests/CMakeFiles/data_test.dir/build
.PHONY : data_test/fast

#=============================================================================
# Target rules for targets named type_test

# Build rule for target.
type_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 type_test
.PHONY : type_test

# fast build rule for target.
type_test/fast:
	$(MAKE) -f type/tests/CMakeFiles/type_test.dir/build.make type/tests/CMakeFiles/type_test.dir/build
.PHONY : type_test/fast

#=============================================================================
# Target rules for targets named code_container_test

# Build rule for target.
code_container_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 code_container_test
.PHONY : code_container_test

# fast build rule for target.
code_container_test/fast:
	$(MAKE) -f type/tests/CMakeFiles/code_container_test.dir/build.make type/tests/CMakeFiles/code_container_test.dir/build
.PHONY : code_container_test/fast

#=============================================================================
# Target rules for targets named ptreferential

# Build rule for target.
ptreferential: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ptreferential
.PHONY : ptreferential

# fast build rule for target.
ptreferential/fast:
	$(MAKE) -f ptreferential/CMakeFiles/ptreferential.dir/build.make ptreferential/CMakeFiles/ptreferential.dir/build
.PHONY : ptreferential/fast

#=============================================================================
# Target rules for targets named ptref_companies_test

# Build rule for target.
ptref_companies_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ptref_companies_test
.PHONY : ptref_companies_test

# fast build rule for target.
ptref_companies_test/fast:
	$(MAKE) -f ptreferential/tests/CMakeFiles/ptref_companies_test.dir/build.make ptreferential/tests/CMakeFiles/ptref_companies_test.dir/build
.PHONY : ptref_companies_test/fast

#=============================================================================
# Target rules for targets named ptref_ng_test

# Build rule for target.
ptref_ng_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ptref_ng_test
.PHONY : ptref_ng_test

# fast build rule for target.
ptref_ng_test/fast:
	$(MAKE) -f ptreferential/tests/CMakeFiles/ptref_ng_test.dir/build.make ptreferential/tests/CMakeFiles/ptref_ng_test.dir/build
.PHONY : ptref_ng_test/fast

#=============================================================================
# Target rules for targets named ptref_odt_level_test

# Build rule for target.
ptref_odt_level_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ptref_odt_level_test
.PHONY : ptref_odt_level_test

# fast build rule for target.
ptref_odt_level_test/fast:
	$(MAKE) -f ptreferential/tests/CMakeFiles/ptref_odt_level_test.dir/build.make ptreferential/tests/CMakeFiles/ptref_odt_level_test.dir/build
.PHONY : ptref_odt_level_test/fast

#=============================================================================
# Target rules for targets named ptref_test

# Build rule for target.
ptref_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ptref_test
.PHONY : ptref_test

# fast build rule for target.
ptref_test/fast:
	$(MAKE) -f ptreferential/tests/CMakeFiles/ptref_test.dir/build.make ptreferential/tests/CMakeFiles/ptref_test.dir/build
.PHONY : ptref_test/fast

#=============================================================================
# Target rules for targets named vehicle_journey_test

# Build rule for target.
vehicle_journey_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vehicle_journey_test
.PHONY : vehicle_journey_test

# fast build rule for target.
vehicle_journey_test/fast:
	$(MAKE) -f ptreferential/tests/CMakeFiles/vehicle_journey_test.dir/build.make ptreferential/tests/CMakeFiles/vehicle_journey_test.dir/build
.PHONY : vehicle_journey_test/fast

#=============================================================================
# Target rules for targets named autocomplete

# Build rule for target.
autocomplete: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autocomplete
.PHONY : autocomplete

# fast build rule for target.
autocomplete/fast:
	$(MAKE) -f autocomplete/CMakeFiles/autocomplete.dir/build.make autocomplete/CMakeFiles/autocomplete.dir/build
.PHONY : autocomplete/fast

#=============================================================================
# Target rules for targets named autocomplete_test

# Build rule for target.
autocomplete_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autocomplete_test
.PHONY : autocomplete_test

# fast build rule for target.
autocomplete_test/fast:
	$(MAKE) -f autocomplete/CMakeFiles/autocomplete_test.dir/build.make autocomplete/CMakeFiles/autocomplete_test.dir/build
.PHONY : autocomplete_test/fast

#=============================================================================
# Target rules for targets named synonym2ed

# Build rule for target.
synonym2ed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 synonym2ed
.PHONY : synonym2ed

# fast build rule for target.
synonym2ed/fast:
	$(MAKE) -f ed/CMakeFiles/synonym2ed.dir/build.make ed/CMakeFiles/synonym2ed.dir/build
.PHONY : synonym2ed/fast

#=============================================================================
# Target rules for targets named poi2ed

# Build rule for target.
poi2ed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poi2ed
.PHONY : poi2ed

# fast build rule for target.
poi2ed/fast:
	$(MAKE) -f ed/CMakeFiles/poi2ed.dir/build.make ed/CMakeFiles/poi2ed.dir/build
.PHONY : poi2ed/fast

#=============================================================================
# Target rules for targets named geopal2ed

# Build rule for target.
geopal2ed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 geopal2ed
.PHONY : geopal2ed

# fast build rule for target.
geopal2ed/fast:
	$(MAKE) -f ed/CMakeFiles/geopal2ed.dir/build.make ed/CMakeFiles/geopal2ed.dir/build
.PHONY : geopal2ed/fast

#=============================================================================
# Target rules for targets named transportation_data_import

# Build rule for target.
transportation_data_import: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 transportation_data_import
.PHONY : transportation_data_import

# fast build rule for target.
transportation_data_import/fast:
	$(MAKE) -f ed/CMakeFiles/transportation_data_import.dir/build.make ed/CMakeFiles/transportation_data_import.dir/build
.PHONY : transportation_data_import/fast

#=============================================================================
# Target rules for targets named ed_executables

# Build rule for target.
ed_executables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ed_executables
.PHONY : ed_executables

# fast build rule for target.
ed_executables/fast:
	$(MAKE) -f ed/CMakeFiles/ed_executables.dir/build.make ed/CMakeFiles/ed_executables.dir/build
.PHONY : ed_executables/fast

#=============================================================================
# Target rules for targets named fare2ed

# Build rule for target.
fare2ed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fare2ed
.PHONY : fare2ed

# fast build rule for target.
fare2ed/fast:
	$(MAKE) -f ed/CMakeFiles/fare2ed.dir/build.make ed/CMakeFiles/fare2ed.dir/build
.PHONY : fare2ed/fast

#=============================================================================
# Target rules for targets named osm2ed

# Build rule for target.
osm2ed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osm2ed
.PHONY : osm2ed

# fast build rule for target.
osm2ed/fast:
	$(MAKE) -f ed/CMakeFiles/osm2ed.dir/build.make ed/CMakeFiles/osm2ed.dir/build
.PHONY : osm2ed/fast

#=============================================================================
# Target rules for targets named osm2ed_lib

# Build rule for target.
osm2ed_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osm2ed_lib
.PHONY : osm2ed_lib

# fast build rule for target.
osm2ed_lib/fast:
	$(MAKE) -f ed/CMakeFiles/osm2ed_lib.dir/build.make ed/CMakeFiles/osm2ed_lib.dir/build
.PHONY : osm2ed_lib/fast

#=============================================================================
# Target rules for targets named ed

# Build rule for target.
ed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ed
.PHONY : ed

# fast build rule for target.
ed/fast:
	$(MAKE) -f ed/CMakeFiles/ed.dir/build.make ed/CMakeFiles/ed.dir/build
.PHONY : ed/fast

#=============================================================================
# Target rules for targets named fusio2ed

# Build rule for target.
fusio2ed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fusio2ed
.PHONY : fusio2ed

# fast build rule for target.
fusio2ed/fast:
	$(MAKE) -f ed/CMakeFiles/fusio2ed.dir/build.make ed/CMakeFiles/fusio2ed.dir/build
.PHONY : fusio2ed/fast

#=============================================================================
# Target rules for targets named gtfs2ed

# Build rule for target.
gtfs2ed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtfs2ed
.PHONY : gtfs2ed

# fast build rule for target.
gtfs2ed/fast:
	$(MAKE) -f ed/CMakeFiles/gtfs2ed.dir/build.make ed/CMakeFiles/gtfs2ed.dir/build
.PHONY : gtfs2ed/fast

#=============================================================================
# Target rules for targets named fare2ed_lib

# Build rule for target.
fare2ed_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fare2ed_lib
.PHONY : fare2ed_lib

# fast build rule for target.
fare2ed_lib/fast:
	$(MAKE) -f ed/CMakeFiles/fare2ed_lib.dir/build.make ed/CMakeFiles/fare2ed_lib.dir/build
.PHONY : fare2ed_lib/fast

#=============================================================================
# Target rules for targets named ed2nav

# Build rule for target.
ed2nav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ed2nav
.PHONY : ed2nav

# fast build rule for target.
ed2nav/fast:
	$(MAKE) -f ed/CMakeFiles/ed2nav.dir/build.make ed/CMakeFiles/ed2nav.dir/build
.PHONY : ed2nav/fast

#=============================================================================
# Target rules for targets named ed2nav_lib

# Build rule for target.
ed2nav_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ed2nav_lib
.PHONY : ed2nav_lib

# fast build rule for target.
ed2nav_lib/fast:
	$(MAKE) -f ed/CMakeFiles/ed2nav_lib.dir/build.make ed/CMakeFiles/ed2nav_lib.dir/build
.PHONY : ed2nav_lib/fast

#=============================================================================
# Target rules for targets named speed_parser_test

# Build rule for target.
speed_parser_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 speed_parser_test
.PHONY : speed_parser_test

# fast build rule for target.
speed_parser_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/speed_parser_test.dir/build.make ed/tests/CMakeFiles/speed_parser_test.dir/build
.PHONY : speed_parser_test/fast

#=============================================================================
# Target rules for targets named route_main_destination_test

# Build rule for target.
route_main_destination_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 route_main_destination_test
.PHONY : route_main_destination_test

# fast build rule for target.
route_main_destination_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/route_main_destination_test.dir/build.make ed/tests/CMakeFiles/route_main_destination_test.dir/build
.PHONY : route_main_destination_test/fast

#=============================================================================
# Target rules for targets named ed2nav_test

# Build rule for target.
ed2nav_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ed2nav_test
.PHONY : ed2nav_test

# fast build rule for target.
ed2nav_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/ed2nav_test.dir/build.make ed/tests/CMakeFiles/ed2nav_test.dir/build
.PHONY : ed2nav_test/fast

#=============================================================================
# Target rules for targets named fare2ed_test

# Build rule for target.
fare2ed_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fare2ed_test
.PHONY : fare2ed_test

# fast build rule for target.
fare2ed_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/fare2ed_test.dir/build.make ed/tests/CMakeFiles/fare2ed_test.dir/build
.PHONY : fare2ed_test/fast

#=============================================================================
# Target rules for targets named fusio_parser_test

# Build rule for target.
fusio_parser_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fusio_parser_test
.PHONY : fusio_parser_test

# fast build rule for target.
fusio_parser_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/fusio_parser_test.dir/build.make ed/tests/CMakeFiles/fusio_parser_test.dir/build
.PHONY : fusio_parser_test/fast

#=============================================================================
# Target rules for targets named gtfs_parser_test

# Build rule for target.
gtfs_parser_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtfs_parser_test
.PHONY : gtfs_parser_test

# fast build rule for target.
gtfs_parser_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/gtfs_parser_test.dir/build.make ed/tests/CMakeFiles/gtfs_parser_test.dir/build
.PHONY : gtfs_parser_test/fast

#=============================================================================
# Target rules for targets named associated_calendar_test

# Build rule for target.
associated_calendar_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 associated_calendar_test
.PHONY : associated_calendar_test

# fast build rule for target.
associated_calendar_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/associated_calendar_test.dir/build.make ed/tests/CMakeFiles/associated_calendar_test.dir/build
.PHONY : associated_calendar_test/fast

#=============================================================================
# Target rules for targets named osm_tags_reader_test

# Build rule for target.
osm_tags_reader_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osm_tags_reader_test
.PHONY : osm_tags_reader_test

# fast build rule for target.
osm_tags_reader_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/osm_tags_reader_test.dir/build.make ed/tests/CMakeFiles/osm_tags_reader_test.dir/build
.PHONY : osm_tags_reader_test/fast

#=============================================================================
# Target rules for targets named fare_parser_test

# Build rule for target.
fare_parser_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fare_parser_test
.PHONY : fare_parser_test

# fast build rule for target.
fare_parser_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/fare_parser_test.dir/build.make ed/tests/CMakeFiles/fare_parser_test.dir/build
.PHONY : fare_parser_test/fast

#=============================================================================
# Target rules for targets named conv_coord_test

# Build rule for target.
conv_coord_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 conv_coord_test
.PHONY : conv_coord_test

# fast build rule for target.
conv_coord_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/conv_coord_test.dir/build.make ed/tests/CMakeFiles/conv_coord_test.dir/build
.PHONY : conv_coord_test/fast

#=============================================================================
# Target rules for targets named shift_stop_times_test

# Build rule for target.
shift_stop_times_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 shift_stop_times_test
.PHONY : shift_stop_times_test

# fast build rule for target.
shift_stop_times_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/shift_stop_times_test.dir/build.make ed/tests/CMakeFiles/shift_stop_times_test.dir/build
.PHONY : shift_stop_times_test/fast

#=============================================================================
# Target rules for targets named poi2ed_test

# Build rule for target.
poi2ed_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poi2ed_test
.PHONY : poi2ed_test

# fast build rule for target.
poi2ed_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/poi2ed_test.dir/build.make ed/tests/CMakeFiles/poi2ed_test.dir/build
.PHONY : poi2ed_test/fast

#=============================================================================
# Target rules for targets named jpp_shape_test

# Build rule for target.
jpp_shape_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jpp_shape_test
.PHONY : jpp_shape_test

# fast build rule for target.
jpp_shape_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/jpp_shape_test.dir/build.make ed/tests/CMakeFiles/jpp_shape_test.dir/build
.PHONY : jpp_shape_test/fast

#=============================================================================
# Target rules for targets named osm2ed_test

# Build rule for target.
osm2ed_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osm2ed_test
.PHONY : osm2ed_test

# fast build rule for target.
osm2ed_test/fast:
	$(MAKE) -f ed/tests/CMakeFiles/osm2ed_test.dir/build.make ed/tests/CMakeFiles/osm2ed_test.dir/build
.PHONY : osm2ed_test/fast

#=============================================================================
# Target rules for targets named connectors

# Build rule for target.
connectors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 connectors
.PHONY : connectors

# fast build rule for target.
connectors/fast:
	$(MAKE) -f ed/connectors/CMakeFiles/connectors.dir/build.make ed/connectors/CMakeFiles/connectors.dir/build
.PHONY : connectors/fast

#=============================================================================
# Target rules for targets named osm_and_gtfs_nav

# Build rule for target.
osm_and_gtfs_nav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osm_and_gtfs_nav
.PHONY : osm_and_gtfs_nav

# fast build rule for target.
osm_and_gtfs_nav/fast:
	$(MAKE) -f ed/docker_tests/CMakeFiles/osm_and_gtfs_nav.dir/build.make ed/docker_tests/CMakeFiles/osm_and_gtfs_nav.dir/build
.PHONY : osm_and_gtfs_nav/fast

#=============================================================================
# Target rules for targets named ntfs_v5_nav

# Build rule for target.
ntfs_v5_nav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ntfs_v5_nav
.PHONY : ntfs_v5_nav

# fast build rule for target.
ntfs_v5_nav/fast:
	$(MAKE) -f ed/docker_tests/CMakeFiles/ntfs_v5_nav.dir/build.make ed/docker_tests/CMakeFiles/ntfs_v5_nav.dir/build
.PHONY : ntfs_v5_nav/fast

#=============================================================================
# Target rules for targets named gtfs_google_example_nav

# Build rule for target.
gtfs_google_example_nav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtfs_google_example_nav
.PHONY : gtfs_google_example_nav

# fast build rule for target.
gtfs_google_example_nav/fast:
	$(MAKE) -f ed/docker_tests/CMakeFiles/gtfs_google_example_nav.dir/build.make ed/docker_tests/CMakeFiles/gtfs_google_example_nav.dir/build
.PHONY : gtfs_google_example_nav/fast

#=============================================================================
# Target rules for targets named ntfs_nav

# Build rule for target.
ntfs_nav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ntfs_nav
.PHONY : ntfs_nav

# fast build rule for target.
ntfs_nav/fast:
	$(MAKE) -f ed/docker_tests/CMakeFiles/ntfs_nav.dir/build.make ed/docker_tests/CMakeFiles/ntfs_nav.dir/build
.PHONY : ntfs_nav/fast

#=============================================================================
# Target rules for targets named datanav_files

# Build rule for target.
datanav_files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 datanav_files
.PHONY : datanav_files

# fast build rule for target.
datanav_files/fast:
	$(MAKE) -f ed/docker_tests/CMakeFiles/datanav_files.dir/build.make ed/docker_tests/CMakeFiles/datanav_files.dir/build
.PHONY : datanav_files/fast

#=============================================================================
# Target rules for targets named poi_nav

# Build rule for target.
poi_nav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 poi_nav
.PHONY : poi_nav

# fast build rule for target.
poi_nav/fast:
	$(MAKE) -f ed/docker_tests/CMakeFiles/poi_nav.dir/build.make ed/docker_tests/CMakeFiles/poi_nav.dir/build
.PHONY : poi_nav/fast

#=============================================================================
# Target rules for targets named run_test

# Build rule for target.
run_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_test
.PHONY : run_test

# fast build rule for target.
run_test/fast:
	$(MAKE) -f ed/docker_tests/CMakeFiles/run_test.dir/build.make ed/docker_tests/CMakeFiles/run_test.dir/build
.PHONY : run_test/fast

#=============================================================================
# Target rules for targets named ed_integration_test

# Build rule for target.
ed_integration_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ed_integration_test
.PHONY : ed_integration_test

# fast build rule for target.
ed_integration_test/fast:
	$(MAKE) -f ed/docker_tests/CMakeFiles/ed_integration_test.dir/build.make ed/docker_tests/CMakeFiles/ed_integration_test.dir/build
.PHONY : ed_integration_test/fast

#=============================================================================
# Target rules for targets named ntfs_dst_nav

# Build rule for target.
ntfs_dst_nav: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ntfs_dst_nav
.PHONY : ntfs_dst_nav

# fast build rule for target.
ntfs_dst_nav/fast:
	$(MAKE) -f ed/docker_tests/CMakeFiles/ntfs_dst_nav.dir/build.make ed/docker_tests/CMakeFiles/ntfs_dst_nav.dir/build
.PHONY : ntfs_dst_nav/fast

#=============================================================================
# Target rules for targets named fare

# Build rule for target.
fare: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fare
.PHONY : fare

# fast build rule for target.
fare/fast:
	$(MAKE) -f fare/CMakeFiles/fare.dir/build.make fare/CMakeFiles/fare.dir/build
.PHONY : fare/fast

#=============================================================================
# Target rules for targets named fare_test

# Build rule for target.
fare_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fare_test
.PHONY : fare_test

# fast build rule for target.
fare_test/fast:
	$(MAKE) -f fare/tests/CMakeFiles/fare_test.dir/build.make fare/tests/CMakeFiles/fare_test.dir/build
.PHONY : fare_test/fast

#=============================================================================
# Target rules for targets named fare_integration_test

# Build rule for target.
fare_integration_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fare_integration_test
.PHONY : fare_integration_test

# fast build rule for target.
fare_integration_test/fast:
	$(MAKE) -f fare/tests/CMakeFiles/fare_integration_test.dir/build.make fare/tests/CMakeFiles/fare_integration_test.dir/build
.PHONY : fare_integration_test/fast

#=============================================================================
# Target rules for targets named proximitylist

# Build rule for target.
proximitylist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 proximitylist
.PHONY : proximitylist

# fast build rule for target.
proximitylist/fast:
	$(MAKE) -f proximity_list/CMakeFiles/proximitylist.dir/build.make proximity_list/CMakeFiles/proximitylist.dir/build
.PHONY : proximitylist/fast

#=============================================================================
# Target rules for targets named proximity_list_test

# Build rule for target.
proximity_list_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 proximity_list_test
.PHONY : proximity_list_test

# fast build rule for target.
proximity_list_test/fast:
	$(MAKE) -f proximity_list/tests/CMakeFiles/proximity_list_test.dir/build.make proximity_list/tests/CMakeFiles/proximity_list_test.dir/build
.PHONY : proximity_list_test/fast

#=============================================================================
# Target rules for targets named workers

# Build rule for target.
workers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 workers
.PHONY : workers

# fast build rule for target.
workers/fast:
	$(MAKE) -f kraken/CMakeFiles/workers.dir/build.make kraken/CMakeFiles/workers.dir/build
.PHONY : workers/fast

#=============================================================================
# Target rules for targets named rt_handling

# Build rule for target.
rt_handling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rt_handling
.PHONY : rt_handling

# fast build rule for target.
rt_handling/fast:
	$(MAKE) -f kraken/CMakeFiles/rt_handling.dir/build.make kraken/CMakeFiles/rt_handling.dir/build
.PHONY : rt_handling/fast

#=============================================================================
# Target rules for targets named apply_disruption

# Build rule for target.
apply_disruption: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apply_disruption
.PHONY : apply_disruption

# fast build rule for target.
apply_disruption/fast:
	$(MAKE) -f kraken/CMakeFiles/apply_disruption.dir/build.make kraken/CMakeFiles/apply_disruption.dir/build
.PHONY : apply_disruption/fast

#=============================================================================
# Target rules for targets named make_disruption_from_chaos

# Build rule for target.
make_disruption_from_chaos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 make_disruption_from_chaos
.PHONY : make_disruption_from_chaos

# fast build rule for target.
make_disruption_from_chaos/fast:
	$(MAKE) -f kraken/CMakeFiles/make_disruption_from_chaos.dir/build.make kraken/CMakeFiles/make_disruption_from_chaos.dir/build
.PHONY : make_disruption_from_chaos/fast

#=============================================================================
# Target rules for targets named fill_disruption_from_database

# Build rule for target.
fill_disruption_from_database: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fill_disruption_from_database
.PHONY : fill_disruption_from_database

# fast build rule for target.
fill_disruption_from_database/fast:
	$(MAKE) -f kraken/CMakeFiles/fill_disruption_from_database.dir/build.make kraken/CMakeFiles/fill_disruption_from_database.dir/build
.PHONY : fill_disruption_from_database/fast

#=============================================================================
# Target rules for targets named kraken

# Build rule for target.
kraken: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kraken
.PHONY : kraken

# fast build rule for target.
kraken/fast:
	$(MAKE) -f kraken/CMakeFiles/kraken.dir/build.make kraken/CMakeFiles/kraken.dir/build
.PHONY : kraken/fast

#=============================================================================
# Target rules for targets named fill_disruption_from_chaos_tests

# Build rule for target.
fill_disruption_from_chaos_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fill_disruption_from_chaos_tests
.PHONY : fill_disruption_from_chaos_tests

# fast build rule for target.
fill_disruption_from_chaos_tests/fast:
	$(MAKE) -f kraken/tests/CMakeFiles/fill_disruption_from_chaos_tests.dir/build.make kraken/tests/CMakeFiles/fill_disruption_from_chaos_tests.dir/build
.PHONY : fill_disruption_from_chaos_tests/fast

#=============================================================================
# Target rules for targets named realtime_test

# Build rule for target.
realtime_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 realtime_test
.PHONY : realtime_test

# fast build rule for target.
realtime_test/fast:
	$(MAKE) -f kraken/tests/CMakeFiles/realtime_test.dir/build.make kraken/tests/CMakeFiles/realtime_test.dir/build
.PHONY : realtime_test/fast

#=============================================================================
# Target rules for targets named disruption_reader_test

# Build rule for target.
disruption_reader_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disruption_reader_test
.PHONY : disruption_reader_test

# fast build rule for target.
disruption_reader_test/fast:
	$(MAKE) -f kraken/tests/CMakeFiles/disruption_reader_test.dir/build.make kraken/tests/CMakeFiles/disruption_reader_test.dir/build
.PHONY : disruption_reader_test/fast

#=============================================================================
# Target rules for targets named data_manager_with_type_data_test

# Build rule for target.
data_manager_with_type_data_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 data_manager_with_type_data_test
.PHONY : data_manager_with_type_data_test

# fast build rule for target.
data_manager_with_type_data_test/fast:
	$(MAKE) -f kraken/tests/CMakeFiles/data_manager_with_type_data_test.dir/build.make kraken/tests/CMakeFiles/data_manager_with_type_data_test.dir/build
.PHONY : data_manager_with_type_data_test/fast

#=============================================================================
# Target rules for targets named worker_test

# Build rule for target.
worker_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 worker_test
.PHONY : worker_test

# fast build rule for target.
worker_test/fast:
	$(MAKE) -f kraken/tests/CMakeFiles/worker_test.dir/build.make kraken/tests/CMakeFiles/worker_test.dir/build
.PHONY : worker_test/fast

#=============================================================================
# Target rules for targets named direct_path_test

# Build rule for target.
direct_path_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 direct_path_test
.PHONY : direct_path_test

# fast build rule for target.
direct_path_test/fast:
	$(MAKE) -f kraken/tests/CMakeFiles/direct_path_test.dir/build.make kraken/tests/CMakeFiles/direct_path_test.dir/build
.PHONY : direct_path_test/fast

#=============================================================================
# Target rules for targets named data_manager_test

# Build rule for target.
data_manager_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 data_manager_test
.PHONY : data_manager_test

# fast build rule for target.
data_manager_test/fast:
	$(MAKE) -f kraken/tests/CMakeFiles/data_manager_test.dir/build.make kraken/tests/CMakeFiles/data_manager_test.dir/build
.PHONY : data_manager_test/fast

#=============================================================================
# Target rules for targets named apply_disruption_test

# Build rule for target.
apply_disruption_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apply_disruption_test
.PHONY : apply_disruption_test

# fast build rule for target.
apply_disruption_test/fast:
	$(MAKE) -f kraken/tests/CMakeFiles/apply_disruption_test.dir/build.make kraken/tests/CMakeFiles/apply_disruption_test.dir/build
.PHONY : apply_disruption_test/fast

#=============================================================================
# Target rules for targets named disruption_periods_test

# Build rule for target.
disruption_periods_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disruption_periods_test
.PHONY : disruption_periods_test

# fast build rule for target.
disruption_periods_test/fast:
	$(MAKE) -f kraken/tests/CMakeFiles/disruption_periods_test.dir/build.make kraken/tests/CMakeFiles/disruption_periods_test.dir/build
.PHONY : disruption_periods_test/fast

#=============================================================================
# Target rules for targets named vptranslator

# Build rule for target.
vptranslator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vptranslator
.PHONY : vptranslator

# fast build rule for target.
vptranslator/fast:
	$(MAKE) -f vptranslator/CMakeFiles/vptranslator.dir/build.make vptranslator/CMakeFiles/vptranslator.dir/build
.PHONY : vptranslator/fast

#=============================================================================
# Target rules for targets named vptranslator_test

# Build rule for target.
vptranslator_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vptranslator_test
.PHONY : vptranslator_test

# fast build rule for target.
vptranslator_test/fast:
	$(MAKE) -f vptranslator/CMakeFiles/vptranslator_test.dir/build.make vptranslator/CMakeFiles/vptranslator_test.dir/build
.PHONY : vptranslator_test/fast

#=============================================================================
# Target rules for targets named lz4_tests

# Build rule for target.
lz4_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lz4_tests
.PHONY : lz4_tests

# fast build rule for target.
lz4_tests/fast:
	$(MAKE) -f lz4_filter/tests/CMakeFiles/lz4_tests.dir/build.make lz4_filter/tests/CMakeFiles/lz4_tests.dir/build
.PHONY : lz4_tests/fast

#=============================================================================
# Target rules for targets named benchmark_full

# Build rule for target.
benchmark_full: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark_full
.PHONY : benchmark_full

# fast build rule for target.
benchmark_full/fast:
	$(MAKE) -f routing/CMakeFiles/benchmark_full.dir/build.make routing/CMakeFiles/benchmark_full.dir/build
.PHONY : benchmark_full/fast

#=============================================================================
# Target rules for targets named benchmark_raptor_cache

# Build rule for target.
benchmark_raptor_cache: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark_raptor_cache
.PHONY : benchmark_raptor_cache

# fast build rule for target.
benchmark_raptor_cache/fast:
	$(MAKE) -f routing/CMakeFiles/benchmark_raptor_cache.dir/build.make routing/CMakeFiles/benchmark_raptor_cache.dir/build
.PHONY : benchmark_raptor_cache/fast

#=============================================================================
# Target rules for targets named routing

# Build rule for target.
routing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 routing
.PHONY : routing

# fast build rule for target.
routing/fast:
	$(MAKE) -f routing/CMakeFiles/routing.dir/build.make routing/CMakeFiles/routing.dir/build
.PHONY : routing/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) -f routing/CMakeFiles/benchmark.dir/build.make routing/CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named journey_test

# Build rule for target.
journey_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 journey_test
.PHONY : journey_test

# fast build rule for target.
journey_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/journey_test.dir/build.make routing/tests/CMakeFiles/journey_test.dir/build
.PHONY : journey_test/fast

#=============================================================================
# Target rules for targets named heat_map_test

# Build rule for target.
heat_map_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heat_map_test
.PHONY : heat_map_test

# fast build rule for target.
heat_map_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/heat_map_test.dir/build.make routing/tests/CMakeFiles/heat_map_test.dir/build
.PHONY : heat_map_test/fast

#=============================================================================
# Target rules for targets named routing_api_test

# Build rule for target.
routing_api_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 routing_api_test
.PHONY : routing_api_test

# fast build rule for target.
routing_api_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/routing_api_test.dir/build.make routing/tests/CMakeFiles/routing_api_test.dir/build
.PHONY : routing_api_test/fast

#=============================================================================
# Target rules for targets named frequency_raptor_test

# Build rule for target.
frequency_raptor_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frequency_raptor_test
.PHONY : frequency_raptor_test

# fast build rule for target.
frequency_raptor_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/frequency_raptor_test.dir/build.make routing/tests/CMakeFiles/frequency_raptor_test.dir/build
.PHONY : frequency_raptor_test/fast

#=============================================================================
# Target rules for targets named reverse_raptor_test

# Build rule for target.
reverse_raptor_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reverse_raptor_test
.PHONY : reverse_raptor_test

# fast build rule for target.
reverse_raptor_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/reverse_raptor_test.dir/build.make routing/tests/CMakeFiles/reverse_raptor_test.dir/build
.PHONY : reverse_raptor_test/fast

#=============================================================================
# Target rules for targets named disruptions_test

# Build rule for target.
disruptions_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disruptions_test
.PHONY : disruptions_test

# fast build rule for target.
disruptions_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/disruptions_test.dir/build.make routing/tests/CMakeFiles/disruptions_test.dir/build
.PHONY : disruptions_test/fast

#=============================================================================
# Target rules for targets named raptor_test

# Build rule for target.
raptor_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 raptor_test
.PHONY : raptor_test

# fast build rule for target.
raptor_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/raptor_test.dir/build.make routing/tests/CMakeFiles/raptor_test.dir/build
.PHONY : raptor_test/fast

#=============================================================================
# Target rules for targets named co2_emission_test

# Build rule for target.
co2_emission_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 co2_emission_test
.PHONY : co2_emission_test

# fast build rule for target.
co2_emission_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/co2_emission_test.dir/build.make routing/tests/CMakeFiles/co2_emission_test.dir/build
.PHONY : co2_emission_test/fast

#=============================================================================
# Target rules for targets named next_stop_time_test

# Build rule for target.
next_stop_time_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 next_stop_time_test
.PHONY : next_stop_time_test

# fast build rule for target.
next_stop_time_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/next_stop_time_test.dir/build.make routing/tests/CMakeFiles/next_stop_time_test.dir/build
.PHONY : next_stop_time_test/fast

#=============================================================================
# Target rules for targets named journey_pattern_container_test

# Build rule for target.
journey_pattern_container_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 journey_pattern_container_test
.PHONY : journey_pattern_container_test

# fast build rule for target.
journey_pattern_container_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/journey_pattern_container_test.dir/build.make routing/tests/CMakeFiles/journey_pattern_container_test.dir/build
.PHONY : journey_pattern_container_test/fast

#=============================================================================
# Target rules for targets named get_stop_times_test

# Build rule for target.
get_stop_times_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_stop_times_test
.PHONY : get_stop_times_test

# fast build rule for target.
get_stop_times_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/get_stop_times_test.dir/build.make routing/tests/CMakeFiles/get_stop_times_test.dir/build
.PHONY : get_stop_times_test/fast

#=============================================================================
# Target rules for targets named isochrone_test

# Build rule for target.
isochrone_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 isochrone_test
.PHONY : isochrone_test

# fast build rule for target.
isochrone_test/fast:
	$(MAKE) -f routing/tests/CMakeFiles/isochrone_test.dir/build.make routing/tests/CMakeFiles/isochrone_test.dir/build
.PHONY : isochrone_test/fast

#=============================================================================
# Target rules for targets named georef

# Build rule for target.
georef: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 georef
.PHONY : georef

# fast build rule for target.
georef/fast:
	$(MAKE) -f georef/CMakeFiles/georef.dir/build.make georef/CMakeFiles/georef.dir/build
.PHONY : georef/fast

#=============================================================================
# Target rules for targets named path_finder_test

# Build rule for target.
path_finder_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 path_finder_test
.PHONY : path_finder_test

# fast build rule for target.
path_finder_test/fast:
	$(MAKE) -f georef/tests/CMakeFiles/path_finder_test.dir/build.make georef/tests/CMakeFiles/path_finder_test.dir/build
.PHONY : path_finder_test/fast

#=============================================================================
# Target rules for targets named street_network_test

# Build rule for target.
street_network_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 street_network_test
.PHONY : street_network_test

# fast build rule for target.
street_network_test/fast:
	$(MAKE) -f georef/tests/CMakeFiles/street_network_test.dir/build.make georef/tests/CMakeFiles/street_network_test.dir/build
.PHONY : street_network_test/fast

#=============================================================================
# Target rules for targets named georef_test

# Build rule for target.
georef_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 georef_test
.PHONY : georef_test

# fast build rule for target.
georef_test/fast:
	$(MAKE) -f georef/tests/CMakeFiles/georef_test.dir/build.make georef/tests/CMakeFiles/georef_test.dir/build
.PHONY : georef_test/fast

#=============================================================================
# Target rules for targets named georef_test_utils

# Build rule for target.
georef_test_utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 georef_test_utils
.PHONY : georef_test_utils

# fast build rule for target.
georef_test_utils/fast:
	$(MAKE) -f georef/tests/CMakeFiles/georef_test_utils.dir/build.make georef/tests/CMakeFiles/georef_test_utils.dir/build
.PHONY : georef_test_utils/fast

#=============================================================================
# Target rules for targets named thermometer

# Build rule for target.
thermometer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thermometer
.PHONY : thermometer

# fast build rule for target.
thermometer/fast:
	$(MAKE) -f time_tables/CMakeFiles/thermometer.dir/build.make time_tables/CMakeFiles/thermometer.dir/build
.PHONY : thermometer/fast

#=============================================================================
# Target rules for targets named time_tables

# Build rule for target.
time_tables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 time_tables
.PHONY : time_tables

# fast build rule for target.
time_tables/fast:
	$(MAKE) -f time_tables/CMakeFiles/time_tables.dir/build.make time_tables/CMakeFiles/time_tables.dir/build
.PHONY : time_tables/fast

#=============================================================================
# Target rules for targets named route_schedules_test

# Build rule for target.
route_schedules_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 route_schedules_test
.PHONY : route_schedules_test

# fast build rule for target.
route_schedules_test/fast:
	$(MAKE) -f time_tables/tests/CMakeFiles/route_schedules_test.dir/build.make time_tables/tests/CMakeFiles/route_schedules_test.dir/build
.PHONY : route_schedules_test/fast

#=============================================================================
# Target rules for targets named departure_boards_test

# Build rule for target.
departure_boards_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 departure_boards_test
.PHONY : departure_boards_test

# fast build rule for target.
departure_boards_test/fast:
	$(MAKE) -f time_tables/tests/CMakeFiles/departure_boards_test.dir/build.make time_tables/tests/CMakeFiles/departure_boards_test.dir/build
.PHONY : departure_boards_test/fast

#=============================================================================
# Target rules for targets named passages_test

# Build rule for target.
passages_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 passages_test
.PHONY : passages_test

# fast build rule for target.
passages_test/fast:
	$(MAKE) -f time_tables/tests/CMakeFiles/passages_test.dir/build.make time_tables/tests/CMakeFiles/passages_test.dir/build
.PHONY : passages_test/fast

#=============================================================================
# Target rules for targets named thermometer_test

# Build rule for target.
thermometer_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thermometer_test
.PHONY : thermometer_test

# fast build rule for target.
thermometer_test/fast:
	$(MAKE) -f time_tables/tests/CMakeFiles/thermometer_test.dir/build.make time_tables/tests/CMakeFiles/thermometer_test.dir/build
.PHONY : thermometer_test/fast

#=============================================================================
# Target rules for targets named tyr_tests

# Build rule for target.
tyr_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tyr_tests
.PHONY : tyr_tests

# fast build rule for target.
tyr_tests/fast:
	$(MAKE) -f tyr/CMakeFiles/tyr_tests.dir/build.make tyr/CMakeFiles/tyr_tests.dir/build
.PHONY : tyr_tests/fast

#=============================================================================
# Target rules for targets named disruption_api

# Build rule for target.
disruption_api: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disruption_api
.PHONY : disruption_api

# fast build rule for target.
disruption_api/fast:
	$(MAKE) -f disruption/CMakeFiles/disruption_api.dir/build.make disruption/CMakeFiles/disruption_api.dir/build
.PHONY : disruption_api/fast

#=============================================================================
# Target rules for targets named disruption_test

# Build rule for target.
disruption_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 disruption_test
.PHONY : disruption_test

# fast build rule for target.
disruption_test/fast:
	$(MAKE) -f disruption/tests/CMakeFiles/disruption_test.dir/build.make disruption/tests/CMakeFiles/disruption_test.dir/build
.PHONY : disruption_test/fast

#=============================================================================
# Target rules for targets named calendar_api

# Build rule for target.
calendar_api: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calendar_api
.PHONY : calendar_api

# fast build rule for target.
calendar_api/fast:
	$(MAKE) -f calendar/CMakeFiles/calendar_api.dir/build.make calendar/CMakeFiles/calendar_api.dir/build
.PHONY : calendar_api/fast

#=============================================================================
# Target rules for targets named calendar_api_test

# Build rule for target.
calendar_api_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calendar_api_test
.PHONY : calendar_api_test

# fast build rule for target.
calendar_api_test/fast:
	$(MAKE) -f calendar/tests/CMakeFiles/calendar_api_test.dir/build.make calendar/tests/CMakeFiles/calendar_api_test.dir/build
.PHONY : calendar_api_test/fast

#=============================================================================
# Target rules for targets named cities

# Build rule for target.
cities: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cities
.PHONY : cities

# fast build rule for target.
cities/fast:
	$(MAKE) -f cities/CMakeFiles/cities.dir/build.make cities/CMakeFiles/cities.dir/build
.PHONY : cities/fast

#=============================================================================
# Target rules for targets named dumpsn

# Build rule for target.
dumpsn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dumpsn
.PHONY : dumpsn

# fast build rule for target.
dumpsn/fast:
	$(MAKE) -f tools/CMakeFiles/dumpsn.dir/build.make tools/CMakeFiles/dumpsn.dir/build
.PHONY : dumpsn/fast

#=============================================================================
# Target rules for targets named equipment_api

# Build rule for target.
equipment_api: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 equipment_api
.PHONY : equipment_api

# fast build rule for target.
equipment_api/fast:
	$(MAKE) -f equipment/CMakeFiles/equipment_api.dir/build.make equipment/CMakeFiles/equipment_api.dir/build
.PHONY : equipment_api/fast

#=============================================================================
# Target rules for targets named equipment_test

# Build rule for target.
equipment_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 equipment_test
.PHONY : equipment_test

# fast build rule for target.
equipment_test/fast:
	$(MAKE) -f equipment/tests/CMakeFiles/equipment_test.dir/build.make equipment/tests/CMakeFiles/equipment_test.dir/build
.PHONY : equipment_test/fast

#=============================================================================
# Target rules for targets named empty_routing_test

# Build rule for target.
empty_routing_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 empty_routing_test
.PHONY : empty_routing_test

# fast build rule for target.
empty_routing_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/empty_routing_test.dir/build.make tests/mock-kraken/CMakeFiles/empty_routing_test.dir/build
.PHONY : empty_routing_test/fast

#=============================================================================
# Target rules for targets named multiple_schedules

# Build rule for target.
multiple_schedules: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multiple_schedules
.PHONY : multiple_schedules

# fast build rule for target.
multiple_schedules/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/multiple_schedules.dir/build.make tests/mock-kraken/CMakeFiles/multiple_schedules.dir/build
.PHONY : multiple_schedules/fast

#=============================================================================
# Target rules for targets named departure_board_test

# Build rule for target.
departure_board_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 departure_board_test
.PHONY : departure_board_test

# fast build rule for target.
departure_board_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/departure_board_test.dir/build.make tests/mock-kraken/CMakeFiles/departure_board_test.dir/build
.PHONY : departure_board_test/fast

#=============================================================================
# Target rules for targets named main_stif_test

# Build rule for target.
main_stif_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_stif_test
.PHONY : main_stif_test

# fast build rule for target.
main_stif_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/main_stif_test.dir/build.make tests/mock-kraken/CMakeFiles/main_stif_test.dir/build
.PHONY : main_stif_test/fast

#=============================================================================
# Target rules for targets named main_autocomplete_test

# Build rule for target.
main_autocomplete_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_autocomplete_test
.PHONY : main_autocomplete_test

# fast build rule for target.
main_autocomplete_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/main_autocomplete_test.dir/build.make tests/mock-kraken/CMakeFiles/main_autocomplete_test.dir/build
.PHONY : main_autocomplete_test/fast

#=============================================================================
# Target rules for targets named basic_schedule_test

# Build rule for target.
basic_schedule_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic_schedule_test
.PHONY : basic_schedule_test

# fast build rule for target.
basic_schedule_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/basic_schedule_test.dir/build.make tests/mock-kraken/CMakeFiles/basic_schedule_test.dir/build
.PHONY : basic_schedule_test/fast

#=============================================================================
# Target rules for targets named main_routing_test

# Build rule for target.
main_routing_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_routing_test
.PHONY : main_routing_test

# fast build rule for target.
main_routing_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/main_routing_test.dir/build.make tests/mock-kraken/CMakeFiles/main_routing_test.dir/build
.PHONY : main_routing_test/fast

#=============================================================================
# Target rules for targets named basic_routing_test

# Build rule for target.
basic_routing_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 basic_routing_test
.PHONY : basic_routing_test

# fast build rule for target.
basic_routing_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/basic_routing_test.dir/build.make tests/mock-kraken/CMakeFiles/basic_routing_test.dir/build
.PHONY : basic_routing_test/fast

#=============================================================================
# Target rules for targets named null_status_test

# Build rule for target.
null_status_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 null_status_test
.PHONY : null_status_test

# fast build rule for target.
null_status_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/null_status_test.dir/build.make tests/mock-kraken/CMakeFiles/null_status_test.dir/build
.PHONY : null_status_test/fast

#=============================================================================
# Target rules for targets named min_nb_journeys_test

# Build rule for target.
min_nb_journeys_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 min_nb_journeys_test
.PHONY : min_nb_journeys_test

# fast build rule for target.
min_nb_journeys_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/min_nb_journeys_test.dir/build.make tests/mock-kraken/CMakeFiles/min_nb_journeys_test.dir/build
.PHONY : min_nb_journeys_test/fast

#=============================================================================
# Target rules for targets named main_ptref_test

# Build rule for target.
main_ptref_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_ptref_test
.PHONY : main_ptref_test

# fast build rule for target.
main_ptref_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/main_ptref_test.dir/build.make tests/mock-kraken/CMakeFiles/main_ptref_test.dir/build
.PHONY : main_ptref_test/fast

#=============================================================================
# Target rules for targets named line_sections_test

# Build rule for target.
line_sections_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 line_sections_test
.PHONY : line_sections_test

# fast build rule for target.
line_sections_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/line_sections_test.dir/build.make tests/mock-kraken/CMakeFiles/line_sections_test.dir/build
.PHONY : line_sections_test/fast

#=============================================================================
# Target rules for targets named timezone_hong_kong_test

# Build rule for target.
timezone_hong_kong_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timezone_hong_kong_test
.PHONY : timezone_hong_kong_test

# fast build rule for target.
timezone_hong_kong_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/timezone_hong_kong_test.dir/build.make tests/mock-kraken/CMakeFiles/timezone_hong_kong_test.dir/build
.PHONY : timezone_hong_kong_test/fast

#=============================================================================
# Target rules for targets named timezone_cape_verde_test

# Build rule for target.
timezone_cape_verde_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timezone_cape_verde_test
.PHONY : timezone_cape_verde_test

# fast build rule for target.
timezone_cape_verde_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/timezone_cape_verde_test.dir/build.make tests/mock-kraken/CMakeFiles/timezone_cape_verde_test.dir/build
.PHONY : timezone_cape_verde_test/fast

#=============================================================================
# Target rules for targets named integration_tests_bin

# Build rule for target.
integration_tests_bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 integration_tests_bin
.PHONY : integration_tests_bin

# fast build rule for target.
integration_tests_bin/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/integration_tests_bin.dir/build.make tests/mock-kraken/CMakeFiles/integration_tests_bin.dir/build
.PHONY : integration_tests_bin/fast

#=============================================================================
# Target rules for targets named main_routing_without_pt_test

# Build rule for target.
main_routing_without_pt_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main_routing_without_pt_test
.PHONY : main_routing_without_pt_test

# fast build rule for target.
main_routing_without_pt_test/fast:
	$(MAKE) -f tests/mock-kraken/CMakeFiles/main_routing_without_pt_test.dir/build.make tests/mock-kraken/CMakeFiles/main_routing_without_pt_test.dir/build
.PHONY : main_routing_without_pt_test/fast

#=============================================================================
# Target rules for targets named chaos_tests

# Build rule for target.
chaos_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chaos_tests
.PHONY : chaos_tests

# fast build rule for target.
chaos_tests/fast:
	$(MAKE) -f tests/chaos/CMakeFiles/chaos_tests.dir/build.make tests/chaos/CMakeFiles/chaos_tests.dir/build
.PHONY : chaos_tests/fast

#=============================================================================
# Target rules for targets named chaos_db_tests

# Build rule for target.
chaos_db_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chaos_db_tests
.PHONY : chaos_db_tests

# fast build rule for target.
chaos_db_tests/fast:
	$(MAKE) -f tests/chaos/CMakeFiles/chaos_db_tests.dir/build.make tests/chaos/CMakeFiles/chaos_db_tests.dir/build
.PHONY : chaos_db_tests/fast

config.o: config.cpp.o

.PHONY : config.o

# target to build an object file
config.cpp.o:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/config.cpp.o
.PHONY : config.cpp.o

config.i: config.cpp.i

.PHONY : config.i

# target to preprocess a source file
config.cpp.i:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/config.cpp.i
.PHONY : config.cpp.i

config.s: config.cpp.s

.PHONY : config.s

# target to generate assembly for a file
config.cpp.s:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/config.cpp.s
.PHONY : config.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... chaos_tests"
	@echo "... datanav_files"
	@echo "... docker_test"
	@echo "... ed_executables"
	@echo "... gtfs_google_example_nav"
	@echo "... integration_tests_bin"
	@echo "... ntfs_dst_nav"
	@echo "... ntfs_nav"
	@echo "... ntfs_v5_nav"
	@echo "... osm_and_gtfs_nav"
	@echo "... poi_nav"
	@echo "... protobuf_files"
	@echo "... run_test"
	@echo "... tidy"
	@echo "... tidy_fix"
	@echo "... tyr_tests"
	@echo "... SimpleAmqpClient"
	@echo "... accessible_test"
	@echo "... aggregation_odt_test"
	@echo "... apply_disruption"
	@echo "... apply_disruption_test"
	@echo "... associated_calendar_test"
	@echo "... autocomplete"
	@echo "... autocomplete_test"
	@echo "... basic_routing_test"
	@echo "... basic_schedule_test"
	@echo "... benchmark"
	@echo "... benchmark_full"
	@echo "... benchmark_raptor_cache"
	@echo "... calendar_api"
	@echo "... calendar_api_test"
	@echo "... chaos_db_tests"
	@echo "... cities"
	@echo "... civetweb"
	@echo "... co2_emission_test"
	@echo "... code_container_test"
	@echo "... comments_test"
	@echo "... config"
	@echo "... connectors"
	@echo "... conv_coord_test"
	@echo "... create_vj_test"
	@echo "... csvreader_test"
	@echo "... data"
	@echo "... data_manager_test"
	@echo "... data_manager_with_type_data_test"
	@echo "... data_test"
	@echo "... datetime_test"
	@echo "... deadline_test"
	@echo "... departure_board_test"
	@echo "... departure_boards_test"
	@echo "... direct_path_test"
	@echo "... disruption_api"
	@echo "... disruption_periods_test"
	@echo "... disruption_reader_test"
	@echo "... disruption_test"
	@echo "... disruptions_test"
	@echo "... dumpsn"
	@echo "... ed"
	@echo "... ed2nav"
	@echo "... ed2nav_lib"
	@echo "... ed2nav_test"
	@echo "... ed_integration_test"
	@echo "... empty_routing_test"
	@echo "... equipment_api"
	@echo "... equipment_test"
	@echo "... fare"
	@echo "... fare2ed"
	@echo "... fare2ed_lib"
	@echo "... fare2ed_test"
	@echo "... fare_integration_test"
	@echo "... fare_parser_test"
	@echo "... fare_test"
	@echo "... fill_disruption_from_chaos_tests"
	@echo "... fill_disruption_from_database"
	@echo "... fill_pb_object_tests"
	@echo "... fill_pb_placemark_test"
	@echo "... frequency_raptor_test"
	@echo "... functions_test"
	@echo "... fusio2ed"
	@echo "... fusio_parser_test"
	@echo "... geopal2ed"
	@echo "... georef"
	@echo "... georef_test"
	@echo "... georef_test_utils"
	@echo "... get_stop_times_test"
	@echo "... gtfs2ed"
	@echo "... gtfs_parser_test"
	@echo "... headsign_test"
	@echo "... heat_map_test"
	@echo "... idx_map_test"
	@echo "... isochrone_test"
	@echo "... journey_pattern_container_test"
	@echo "... journey_test"
	@echo "... jpp_shape_test"
	@echo "... kraken"
	@echo "... line_sections_test"
	@echo "... lru_test"
	@echo "... lz4_tests"
	@echo "... main_autocomplete_test"
	@echo "... main_ptref_test"
	@echo "... main_routing_test"
	@echo "... main_routing_without_pt_test"
	@echo "... main_stif_test"
	@echo "... make_disruption_from_chaos"
	@echo "... map_find_test"
	@echo "... min_nb_journeys_test"
	@echo "... multi_obj_pool_test"
	@echo "... multi_polygon_map_test"
	@echo "... multiple_schedules"
	@echo "... next_stop_time_test"
	@echo "... null_status_test"
	@echo "... obj_factory_test"
	@echo "... osm2ed"
	@echo "... osm2ed_lib"
	@echo "... osm2ed_test"
	@echo "... osm_tags_reader_test"
	@echo "... passages_test"
	@echo "... path_finder_test"
	@echo "... pb_converter"
	@echo "... pb_lib"
	@echo "... poi2ed"
	@echo "... poi2ed_test"
	@echo "... prometheus-cpp-core"
	@echo "... prometheus-cpp-pull"
	@echo "... proximity_list_test"
	@echo "... proximitylist"
	@echo "... ptref_companies_test"
	@echo "... ptref_ng_test"
	@echo "... ptref_odt_level_test"
	@echo "... ptref_test"
	@echo "... ptreferential"
	@echo "... rabbitmq-static"
	@echo "... raptor_test"
	@echo "... realtime_test"
	@echo "... reverse_raptor_test"
	@echo "... route_main_destination_test"
	@echo "... route_schedules_test"
	@echo "... routing"
	@echo "... routing_api_test"
	@echo "... rt_handling"
	@echo "... shift_stop_times_test"
	@echo "... speed_parser_test"
	@echo "... street_network_test"
	@echo "... synonym2ed"
	@echo "... thermometer"
	@echo "... thermometer_test"
	@echo "... time_tables"
	@echo "... timezone_cape_verde_test"
	@echo "... timezone_hong_kong_test"
	@echo "... transportation_data_import"
	@echo "... type_test"
	@echo "... types"
	@echo "... utils"
	@echo "... utils_test"
	@echo "... vehicle_journey_test"
	@echo "... vptranslator"
	@echo "... vptranslator_test"
	@echo "... worker_test"
	@echo "... workers"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

