# sonar-project.properties

# Project
sonar.host.url=https://sonarcloud.io
sonar.organization=hove-io
sonar.projectKey=Hove_navitia
sonar.projectName=Navitia

# Config
sonar.sources=source
sonar.exclusions=source/third_party/**

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
