FROM debian:10-slim

# update package list from providers
RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y ca-certificates  dh-python && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

 COPY docker/ca-certificates/*.crt /usr/local/share/ca-certificates/
 COPY docker/build_kraken.sh /build_kraken.sh
 RUN chmod +x /build_kraken.sh
 RUN update-ca-certificates
 # Python 'requests' package handle its own CA certificate list
 # Let's force it to use the OS's list
 ENV REQUESTS_CA_BUNDLE /etc/ssl/certs

CMD ["/build_kraken.sh"]
