FROM navitia/master

# used for data migrations
COPY source/sql/alembic /usr/share/navitia/ed/alembic
COPY source/sql/requirements.txt /tmp/requirements.txt
COPY source/cities /usr/share/navitia/cities
COPY docker/templates/* /templates/

COPY navitia-common_*.deb navitia-tyr_*.deb ./
COPY docker/run_tyr_beat.sh /

RUN apt-get update \
    && apt install -y python python-pip git postgresql-client libgeos-c1v5 libpq5 gettext-base jq python-pip ./navitia-common_*.deb ./navitia-tyr_*.deb \
    && apt-get clean \
    && rm -rf navitia-common_*.deb navitia-tyr_*.deb

# install ed migrations requirements
RUN pip install -r /tmp/requirements.txt

# install tyr requirements
RUN pip install --no-cache-dir -r /usr/share/tyr/requirements.txt

RUN chmod +x /run_tyr_beat.sh

WORKDIR /usr/share/tyr/

ENTRYPOINT ["bash", "/run_tyr_beat.sh"]
