FROM navitia/master

COPY source/sql/alembic /usr/share/navitia/ed/alembic
COPY source/sql/requirements.txt /tmp/requirements.txt
COPY source/cities /usr/share/navitia/cities
COPY docker/templates/* /templates/

RUN apt-get update \
    && apt install -y python python-pip git libpq-dev postgresql-client gettext-base \
    && apt-get clean

RUN pip install -r /tmp/requirements.txt

COPY docker/instances_configuration.sh /
RUN chmod +x /instances_configuration.sh

ENTRYPOINT ["/bin/bash","/instances_configuration.sh"]
