# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import realtime_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='task.proto',
  package='pbnavitia',
  serialized_pb='\n\ntask.proto\x12\tpbnavitia\x1a\x0erealtime.proto\"\x94\x01\n\x04Task\x12!\n\x06\x61\x63tion\x18\x01 \x02(\x0e\x32\x11.pbnavitia.Action\x12,\n\x07message\x18\x03 \x01(\x0b\x32\x1b.pbnavitia.realtime.Message\x12;\n\x0f\x61t_perturbation\x18\x04 \x01(\x0b\x32\".pbnavitia.realtime.AtPerturbation*6\n\x06\x41\x63tion\x12\n\n\x06RELOAD\x10\x00\x12\x0b\n\x07MESSAGE\x10\x01\x12\x13\n\x0f\x41T_PERTURBATION\x10\x02')

_ACTION = descriptor.EnumDescriptor(
  name='Action',
  full_name='pbnavitia.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='RELOAD', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MESSAGE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='AT_PERTURBATION', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=192,
  serialized_end=246,
)


RELOAD = 0
MESSAGE = 1
AT_PERTURBATION = 2



_TASK = descriptor.Descriptor(
  name='Task',
  full_name='pbnavitia.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='action', full_name='pbnavitia.Task.action', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='pbnavitia.Task.message', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='at_perturbation', full_name='pbnavitia.Task.at_perturbation', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=190,
)

_TASK.fields_by_name['action'].enum_type = _ACTION
_TASK.fields_by_name['message'].message_type = realtime_pb2._MESSAGE
_TASK.fields_by_name['at_perturbation'].message_type = realtime_pb2._ATPERTURBATION
DESCRIPTOR.message_types_by_name['Task'] = _TASK

class Task(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASK
  
  # @@protoc_insertion_point(class_scope:pbnavitia.Task)

# @@protoc_insertion_point(module_scope)
