FROM navitia/master

COPY navitia-common_*.deb ./
COPY navitia-tyr_*.deb ./

# install navitia-common package
RUN dpkg -i ./navitia-common_*.deb || exit 0
RUN apt-get install -f -y --force-yes

# install navitia-tyr package
RUN dpkg -i ./navitia-tyr_*.deb || exit 0
RUN apt-get install -f -y --force-yes

# install postgresql-client
RUN apt-get install -y --force-yes postgresql-client

# install tyr requirements
RUN pip install --no-cache-dir -r /usr/share/tyr/requirements.txt

# install uwsgi
RUN pip install uwsgi

WORKDIR /usr/src/app/
RUN cp /usr/bin/manage_tyr.py /usr/src/app/manage_tyr.py

COPY docker/run_tyr_web.sh /usr/src/app/run.sh
RUN chmod +x /usr/src/app/run.sh

RUN ln -s /usr/share/tyr/migrations migrations

ENTRYPOINT ["bash", "/usr/src/app/run.sh" ]
