FROM navitia/master


COPY source/sql/alembic /usr/share/navitia/ed/alembic
COPY source/sql/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

COPY source/cities /usr/share/navitia/cities

COPY docker/instances_configuration.sh /
COPY docker/templates/* /templates/



ENTRYPOINT [ "sh", "-x", "/instances_configuration.sh" ]
