FROM navitia/master

COPY navitia-common_*.deb ./
COPY navitia-jormungandr_*.deb ./

# install navitia-common package
RUN dpkg -i ./navitia-common_*.deb || exit 0
RUN apt-get install -f -y --force-yes

# install navitia-jormun package
RUN dpkg -i ./navitia-jormungandr_*.deb || exit 0
RUN apt-get install -f -y --force-yes

RUN apt-get install -y --force-yes apache2 \
    && apt-get clean \
    && apt-get autoremove

# install jormungandr requirements
RUN pip install --no-cache-dir -r /usr/share/jormungandr/requirements.txt \
    && pip install uwsgi

# Add apache config
RUN rm /etc/apache2/sites-available/000-default.conf
COPY navitia/docker/apache/jormungandr.default.conf /etc/apache2/sites-available/000-default.conf
COPY navitia/docker/apache/apache2.conf /etc/apache2/apache2.conf
COPY navitia/docker/apache/envvars /etc/apache2/envvars
COPY navitia/docker/apache/logformat.conf /etc/apache2/conf-available/logformat.conf

# Enable site and modes
RUN a2ensite 000-default.conf \
    && a2enmod rewrite \
    && a2enmod proxy \
    && a2enmod proxy_balancer \
    && a2enmod proxy_http \
    && a2enconf logformat.conf

# Redirect apache log output to docker log collector
RUN ln -sf /proc/self/fd/1 /var/log/apache2/access.log \
    && ln -sf /proc/self/fd/2 /var/log/apache2/error.log

# jormungandr wsgi
COPY navitia/docker/jormungandr.wsgi /usr/src/app/jormungandr.wsgi
COPY navitia/docker/run_jormungandr.sh /usr/src/app/run.sh

WORKDIR /usr/src/app/

HEALTHCHECK CMD curl -f http://localhost/v1 || exit 1

ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION_VERSION=2

EXPOSE 80

ENTRYPOINT [ "/usr/src/app/run.sh" ]
