FROM navitia/master

COPY navitia-common_*.deb navitia-tyr_*.deb ./

RUN apt-get update \
    && apt install -y --force-yes jq

# used for data migrations
COPY source/sql/alembic /usr/share/navitia/ed/alembic
COPY source/sql/requirements.txt /tmp/requirements.txt
COPY source/cities /usr/share/navitia/cities
COPY docker/templates/* /templates/

# install navitia-common package
RUN dpkg -i ./navitia-common_*.deb || exit 0

# install navitia-tyr package
RUN dpkg -i ./navitia-tyr_*.deb || exit 0

RUN apt-get install -f -y --force-yes

RUN rm navitia-common_*.deb  \
    navitia-tyr_*.deb

# install ed migrations requirements
RUN pip install -r /tmp/requirements.txt

# install tyr requirements
RUN pip install --no-cache-dir -r /usr/share/tyr/requirements.txt

# install postgresql-client
RUN apt-get install -y --force-yes postgresql-client

COPY docker/run_tyr_beat.sh /
RUN chmod +x /run_tyr_beat.sh

WORKDIR /usr/share/tyr/
ENTRYPOINT ["bash", "/run_tyr_beat.sh"]
