FROM navitia/master

# copy package from context inside the docker
COPY mock-kraken_*.deb ./

# install mock-kraken package
RUN dpkg -i ./mock-kraken_*.deb
RUN apt-get install -f -y --force-yes

RUN mkdir -p /srv/kraken
RUN cp /usr/bin/main_routing_test /srv/kraken/
RUN cp /usr/bin/departure_board_test /srv/kraken/
WORKDIR /srv/kraken
EXPOSE 30000
ENV KRAKEN_GENERAL_zmq_socket=tcp://*:30000
ENV KRAKEN_GENERAL_log_level=INFO

CMD [""]

