FROM navitia/master

COPY navitia-common_*.deb ./
COPY navitia-tyr_*.deb ./

# install navitia-common package
RUN dpkg -i ./navitia-common_*.deb || exit 0
RUN apt-get install -f -y

# install navitia-tyr package
RUN dpkg -i ./navitia-tyr_*.deb || exit 0
RUN apt-get install -f -y

# install tyr requirements
RUN pip install --no-cache-dir -r /usr/share/tyr/requirements.txt

# install postgresql-client
RUN apt-get install -y postgresql-client


COPY navitia/docker/run_tyr_beat.sh /
RUN chmod +x /run_tyr_beat.sh

WORKDIR /usr/share/tyr/
CMD ["sh", "/run_tyr_beat.sh"]
