FROM 162230498103.dkr.ecr.eu-west-1.amazonaws.com/mutable-debian11_dev:latest

RUN apt-get update && apt-get install -y git wget

RUN git config --global --add safe.directory /navitia/navitia

COPY docker/build_kraken_deb11.sh /build_navitia.sh
RUN chmod +x /build_navitia.sh

# install a more recent version of CMake
RUN apt-get remove --yes cmake \
    && cd /tmp \
    && wget https://cmake.org/files/v3.18/cmake-3.18.6-Linux-x86_64.tar.gz \
    && tar xf cmake-3.18.6-Linux-x86_64.tar.gz --strip-components=1 --directory=/usr/local \
    && rm -f cmake-3.18.6-Linux-x86_64.tar.gz \
    && cd -

ENTRYPOINT ["bash", "/build_navitia.sh"]
