FROM debian:bullseye-slim


COPY ./source/sql/alembic /usr/share/navitia/ed/alembic
COPY ./source/sql/requirements.txt /tmp/requirements.txt
COPY ./source/cities /usr/share/navitia/cities
COPY ./docker/templates/* /templates/

COPY docker/instances_configuration.sh /
RUN chmod +x /instances_configuration.sh

RUN apt update --fix-missing \
    && apt install -y libpq5 python3.9-dev python3-pip postgresql-client gettext-base \
    && pip3 install --no-cache-dir -U -r /tmp/requirements.txt \
    && apt autoremove -y

ENTRYPOINT ["/bin/bash","/instances_configuration.sh"]
