# Compilation of rust binaries from tartare-tools
FROM rust:1.82-bullseye as tartare-tools

ARG TARTARE_TOOLS_VERSION="v0.46.0"
ARG GITHUB_TOKEN
RUN git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/hove-io/".insteadOf "ssh://git@github.com/hove-io/"
RUN git clone -b ${TARTARE_TOOLS_VERSION} --depth 1 https://x-access-token:${GITHUB_TOKEN}@github.com/hove-io/tartare-tools

RUN cd tartare-tools \
    && cargo  build --release -p enrich-ntfs-with-addresses \
    && cargo  build --release -p split-trip-geometries \
    && cp target/release/enrich-ntfs-with-addresses /usr/bin/ \
    && cp target/release/split-trip-geometries /usr/bin/ \
    && cd .. \
    && rm -rf tartare-tools

FROM debian:bullseye-slim






# # RUN apt install -y --force-yes unzip
# # RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
# # RUN unzip awscliv2.zip
# # RUN ./aws/install
# WORKDIR /usr/src/app/

# binaries
COPY --from=tartare-tools /usr/bin/enrich-ntfs-with-addresses /bin/
COPY --from=tartare-tools /usr/bin/split-trip-geometries /bin/

COPY ./source/navitiacommon ./navitiacommon
COPY ./source/tyr ./tyr
# COPY ./docker/ca-certificates/*.crt /usr/local/share/ca-certificates/
COPY ./docker/run_tyr_worker.sh /run.sh
# COPY ./source/sql/requirements.txt /tmp/requirements.txt
# COPY ./source/cities /usr/share/navitia/cities
# COPY ./docker/templates/* /templates/

RUN chmod +x /run.sh

# COPY navitia-common_*deb navitia-tyr_*.deb navitia-ed_*.deb  navitia-cities_*.deb  mimirsbrunn7_jessie-*.deb  cosmogony2cities_*.deb  mimirsbrunn-config-*.deb ./

# # install navitia-common package
# RUN dpkg -i ./navitia-common_*.deb || exit 0
# # install navitia-tyr package
# RUN dpkg -i ./navitia-tyr_*.deb || exit 0
# # install navitia-ed package
# RUN dpkg -i ./navitia-ed_*.deb || exit 0
# # install navitia-cities package
# RUN dpkg -i ./navitia-cities_*.deb || exit 0
# # install navitia-mimirsbrunn package
# RUN dpkg -i ./mimirsbrunn7_jessie-*.deb \
#         # install cosmogony2cities package
#         ./cosmogony2cities*.deb \
#         # install conf mimir package
#         ./mimirsbrunn-config-*.deb

# COPY ./docker_build/kraken/kraken /usr/bin/kraken
# RUN chmod +x /usr/bin/kraken

# RUN apt-get install -f -y --force-yes

# RUN rm navitia-common_*deb \
#     navitia-tyr_*.deb \
#     navitia-cities_*.deb \
#     navitia-ed_*.deb \
#     mimirsbrunn-config-*.deb \
#     mimirsbrunn7_jessie-*.deb \
#     cosmogony2cities_*.deb




# EXPOSE 5000


# RUN apt install psycopg2

RUN apt-get update --fix-missing \
    && apt-get install -y --force-yes libgeos-dev libpq5 python3.9-dev python3-pip git ca-certificates postgresql-client gettext-base jq \
    && update-ca-certificates \
    && (cd navitiacommon && python3 setup.py install) \
    && (cd tyr && python3 setup.py install && pip3 install --no-cache-dir -U -r requirements.txt)\
    # && pip3 install --no-cache-dir -U -r /tmp/requirements.txt \
    && apt-get purge -y \
        git \
    && apt-get autoremove -y
# COPY source/monitor && python2.7 setup.py install --root=$(CURDIR)/debian/tmp --install-layout=deb

# TODO change the user to remove this ugly C_FORCE_ROOT
ENV C_FORCE_ROOT=1
ENV TYR_WORKER_N_PROC=1

# COPY docker/run_tyr_worker.sh /usr/src/app/
# RUN chmod +x /usr/src/app/run_tyr_worker.sh
# ENTRYPOINT ["bash", "/usr/src/app/run_tyr_worker.sh"]

ENTRYPOINT ["bash", "/run.sh"]