FROM 162230498103.dkr.ecr.eu-west-1.amazonaws.com/mutable-debian11_dev:latest

RUN apt-get update && apt-get install -y git wget

RUN git config --global --add safe.directory /navitia/navitia

COPY docker/build_kraken_deb11.sh /build_navitia.sh
RUN chmod +x /build_navitia.sh

ENTRYPOINT ["bash", "/build_navitia.sh"]
