FROM python:3.11-slim-bullseye

COPY source/ /navitia/source/

RUN apt clean \
    && rm -rf /var/lib/apt/lists/* \
    && printf 'deb [check-valid-until=no] http://archive.debian.org/debian/ bullseye main\ndeb [check-valid-until=no] http://archive.debian.org/debian/ bullseye-updates main\ndeb [check-valid-until=no] http://snapshot.debian.org/archive/debian-security/20260903T000000Z bullseye-security main\n' > /etc/apt/sources.list \
    && apt-get -o Acquire::Check-Valid-Until=false update -y \
    && apt install -o Acquire::Retries=10 -y libpq5 git zip jq curl \
    libboost-all-dev \
    libprotobuf-dev \
    liblog4cplus-2.0.5 \
    libzmq3-dev \
    libpqxx-dev \
    libgoogle-perftools4 \
    libosmpbf-dev \
    libproj-dev \
    && pip install --no-cache-dir -U -r /navitia/source/eitri/requirements.txt\
    && apt autoremove -y

# binaries from navitia
COPY ./docker_build/ed/ed2nav /usr/bin/ed2nav
COPY ./docker_build/ed/fare2ed /usr/bin/fare2ed
COPY ./docker_build/ed/fusio2ed /usr/bin/fusio2ed
COPY ./docker_build/ed/geopal2ed /usr/bin/geopal2ed
COPY ./docker_build/ed/gtfs2ed /usr/bin/gtfs2ed
COPY ./docker_build/ed/osm2ed /usr/bin/osm2ed
COPY ./docker_build/ed/poi2ed /usr/bin/poi2ed

CMD [""]
