FROM python:3.11-slim-bullseye

WORKDIR /usr/share/tyr/

COPY ./source/navitiacommon ./navitiacommon
COPY ./source/tyr ./tyr
COPY ./docker/ca-certificates/*.crt /usr/local/share/ca-certificates/
COPY ./docker/run_tyr_beat.sh /run_tyr_beat.sh
COPY ./source/sql/alembic /usr/share/navitia/ed/alembic
COPY ./source/sql/requirements.txt /tmp/requirements.txt
COPY ./source/cities /usr/share/navitia/cities
COPY ./docker/templates/* /templates/
RUN chmod +x /run_tyr_beat.sh

RUN apt clean \
    && apt update --fix-missing \
    && apt install -o Acquire::Retries=10 -y libgeos-dev libpq5 git ca-certificates postgresql-client gettext-base jq gcc \
    && update-ca-certificates \
    && (cd navitiacommon && python setup.py install) \
    && (cd tyr && python setup.py install && pip install --no-cache-dir -U -r requirements.txt)\
    && pip install --no-cache-dir -U -r /tmp/requirements.txt \
    && apt purge -y git \
    && apt autoremove -y

ENTRYPOINT ["bash", "/run_tyr_beat.sh"]
