FROM python:3.11-slim-bullseye

WORKDIR /srv/kraken

COPY ./docker/ca-certificates/*.crt /usr/local/share/ca-certificates/
COPY ./source/monitor /srv/monitor_kraken

RUN apt clean \
    && rm -rf /var/lib/apt/lists/* \
    && printf 'deb [check-valid-until=no] http://archive.debian.org/debian/ bullseye main\ndeb [check-valid-until=no] http://archive.debian.org/debian/ bullseye-updates main\ndeb [check-valid-until=no] http://snapshot.debian.org/archive/debian-security/20260903T000000Z bullseye-security main\n' > /etc/apt/sources.list \
    && apt-get -o Acquire::Check-Valid-Until=false update -y \
    && apt install -o Acquire::Retries=10 -y ca-certificates \
    && update-ca-certificates \
    && apt install -o Acquire::Retries=10 -y libgoogle-perftools4 \
    libboost-all-dev \
    libprotobuf-dev \
    liblog4cplus-2.0.5 \
    libzmq3-dev \
    libpqxx-dev \
    curl \
    netcat \
    && (cd /srv/monitor_kraken && python3.11 -m pip install .  && python3.11 -m pip install --no-cache-dir -U -r requirements.txt) \
    && apt purge -y \
    && apt autoremove -y

RUN ln -s /usr/local/lib/python3.11/site-packages/monitor_kraken/app.py monitor_kraken

COPY docker/run_kraken_deb11.sh /usr/src/app/run_kraken.sh
RUN chmod +x /usr/src/app/run_kraken.sh

COPY ./docker_build/kraken/kraken /usr/bin/kraken
RUN chmod +x /usr/bin/kraken

RUN mkdir /libkeepalive
COPY ./docker_build/build_libkeepalive/libkeepalive.so /libkeepalive/.

# User timeout = 300 + 30 * 6 = 480s
ENV KEEPIDLE=300
ENV KEEPCNT=6
ENV KEEPINTVL=30
# if you are willing to use settings from os, set KEEPALIVE to off
# ENV KEEPALIVE=Off

ENV KRAKEN_GENERAL_zmq_socket=tcp://0.0.0.0:30000
ENV KRAKEN_GENERAL_log_level=INFO
HEALTHCHECK CMD nc -z localhost 30000 || exit 1
EXPOSE 30000
EXPOSE 5000


ENTRYPOINT ["bash", "/usr/src/app/run_kraken.sh"]
