#!/bin/bash
case "$1" in
    configure)
        chmod +x /usr/share/navitia/
        chmod +x /usr/share/navitia/scripts/
        chmod +x /usr/share/navitia/scripts/{navimake_updater,update_data}.sh
        chown root:www-data /usr/share/navitia/scripts/{navimake_updater,update_data}.sh
        chown -R www-data:www-data /var/log/gunicorn/
        ;;
esac
