#!/bin/bash
case "$1" in
    configure)
        chmod +x /usr/share/navitia/
        chmod +x /usr/share/navitia/scripts/
        chmod +x /usr/share/navitia/scripts/{navimake_updater,update_data}.sh
        chmod +r -R /usr/share/navitia/
        chmod +rx -R /srv/jormungandr/
        chown root:www-data /usr/share/navitia/scripts/{navimake_updater,update_data}.sh
        ;;
esac
