#!/bin/bash

case "$1" in
    install)
        # user who launch daemons:
        useradd --home /srv/spam --create-home --shell /bin/sh --comment "spam daemon" spam


        # pid for daemons
        mkdir -p /var/run/spam
        chown spam /var/run/spam

        # Rotation is handled by spam
        mkdir -p /var/log/spam
        chown spam /var/log/spam/
        ;;
esac
 
