"""add a minimum duration for bss in the scenario destineo

Revision ID: 1b1bc5bf715a
Revises: 22cf37e67aca
Create Date: 2014-11-26 16:31:06.657355

"""

# revision identifiers, used by Alembic.
revision = '1b1bc5bf715a'
down_revision = '22cf37e67aca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column('destineo_min_bss', sa.Integer(), nullable=False, server_default='420'))
    op.add_column(
        'instance', sa.Column('destineo_min_tc_with_bss', sa.Integer(), nullable=False, server_default='300')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'destineo_min_tc_with_bss')
    op.drop_column('instance', 'destineo_min_bss')
    ### end Alembic commands ###
