"""add two column in instance: "min_duration_too_long_journey" and "factor_too_long_journey"

Revision ID: 20e7cc528c9e
Revises: 5423986c3a51
Create Date: 2014-12-09 16:29:38.521076

"""

# revision identifiers, used by Alembic.
revision = '20e7cc528c9e'
down_revision = '5423986c3a51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'instance', sa.Column('factor_too_long_journey', sa.Float(), nullable=False, server_default='4')
    )
    op.add_column(
        'instance',
        sa.Column('min_duration_too_long_journey', sa.Integer(), nullable=False, server_default='900'),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'min_duration_too_long_journey')
    op.drop_column('instance', 'factor_too_long_journey')
    ### end Alembic commands ###
