"""add configuration for scenario destineo

Revision ID: 22cf37e67aca
Revises: 400ee32cef3b
Create Date: 2014-11-13 18:36:06.571380

"""

# revision identifiers, used by Alembic.
revision = '22cf37e67aca'
down_revision = '400ee32cef3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column('destineo_min_bike', sa.Integer(), nullable=False, server_default='300'))
    op.add_column('instance', sa.Column('destineo_min_car', sa.Integer(), nullable=False, server_default='300'))
    op.add_column(
        'instance', sa.Column('destineo_min_tc_with_bike', sa.Integer(), nullable=False, server_default='300')
    )
    op.add_column(
        'instance', sa.Column('destineo_min_tc_with_car', sa.Integer(), nullable=False, server_default='300')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'destineo_min_tc_with_car')
    op.drop_column('instance', 'destineo_min_tc_with_bike')
    op.drop_column('instance', 'destineo_min_car')
    op.drop_column('instance', 'destineo_min_bike')
    ### end Alembic commands ###
