"""add admin lvl to import in autocomplete_parameters

Revision ID: 2d56e135cd38
Revises: 596a1d3d5157
Create Date: 2016-04-21 14:48:31.273861

"""

# revision identifiers, used by Alembic.
revision = '2d56e135cd38'
down_revision = '596a1d3d5157'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('autocomplete_parameter', sa.Column('admin_level', postgresql.ARRAY(sa.Integer()), nullable=False, server_default='{8}'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('autocomplete_parameter', 'admin_level')
    ### end Alembic commands ###
