"""Add traveler profile table

Revision ID: 2e0ac7e0a7a7
Revises: 1414da92b3ca
Create Date: 2015-08-18 17:44:32.460413

"""

# revision identifiers, used by Alembic.
revision = '2e0ac7e0a7a7'
down_revision = '1414da92b3ca'

from alembic import op, context
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.types import Enum


def upgrade():
    # https://bitbucket.org/zzzeek/alembic/issues/159/opdrop_column-never-ends-with-an-enum
    # This enum is declared explicitly because error occurred when declaring ARRAY(ENUM(.....))
    fallback_mode = Enum('walking', 'car', 'bss', 'bike', name='fallback_mode')
    fallback_mode.create(bind=op.get_bind())

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveler_profile',
    sa.Column('coverage_id', sa.Integer(), nullable=False),
    sa.Column('traveler_type', sa.Enum('standard', 'slow_walker', 'fast_walker', 'luggage', 'wheelchair', 'cyclist', 'motorist', name='traveler_type'), nullable=False),
    sa.Column('walking_speed', sa.Float(), nullable=False),
    sa.Column('bike_speed', sa.Float(), nullable=False),
    sa.Column('bss_speed', sa.Float(), nullable=False),
    sa.Column('car_speed', sa.Float(), nullable=False),
    sa.Column('wheelchair', sa.Boolean(), nullable=False),
    sa.Column('max_walking_duration_to_pt', sa.Integer(), nullable=False),
    sa.Column('max_bike_duration_to_pt', sa.Integer(), nullable=False),
    sa.Column('max_bss_duration_to_pt', sa.Integer(), nullable=False),
    sa.Column('max_car_duration_to_pt', sa.Integer(), nullable=False),
    sa.Column('first_section_mode', postgresql.ARRAY(fallback_mode), nullable=False),
    sa.Column('last_section_mode', postgresql.ARRAY(fallback_mode), nullable=False),
    sa.ForeignKeyConstraint(['coverage_id'], ['instance.id'], ),
    sa.PrimaryKeyConstraint('coverage_id', 'traveler_type')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traveler_profile')
    ### end Alembic commands ###

    #https://bitbucket.org/zzzeek/alembic/issues/159/opdrop_column-never-ends-with-an-enum
    sa.Enum(name='fallback_mode').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='traveler_type').drop(op.get_bind(), checkfirst=False)
