"""empty message

Revision ID: 3e6c7a8fbdb2
Revises: d8ce67cdcaf
Create Date: 2014-07-07 15:39:18.922191

"""

# revision identifiers, used by Alembic.
revision = '3e6c7a8fbdb2'
down_revision = 'd8ce67cdcaf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ptobject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('external_code', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_index('ix_ptobject_external_code', 'ptobject', ['external_code'], unique=False)
    op.add_column('stop_area', sa.Column('timezone', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stop_area', 'timezone')
    op.drop_index('ix_ptobject_external_code', 'ptobject')
    op.drop_table('ptobject')
    ### end Alembic commands ###
