"""add configuration of speed and max_duration_to_pt for each instances

Revision ID: 400ee32cef3b
Revises: 22d1885d1265
Create Date: 2014-10-15 16:35:21.729574

"""

# revision identifiers, used by Alembic.
revision = '400ee32cef3b'
down_revision = '22d1885d1265'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic ###
    # server_default require a string...
    op.add_column('instance', sa.Column('bike_speed', sa.Float(), nullable=False, server_default='4.1'))
    op.add_column('instance', sa.Column('bss_speed', sa.Float(), nullable=False, server_default='4.1'))
    op.add_column('instance', sa.Column('car_speed', sa.Float(), nullable=False, server_default='11.11'))
    op.add_column(
        'instance', sa.Column('max_bike_duration_to_pt', sa.Integer(), nullable=False, server_default='900')
    )
    op.add_column(
        'instance', sa.Column('max_bss_duration_to_pt', sa.Integer(), nullable=False, server_default='900')
    )
    op.add_column(
        'instance', sa.Column('max_car_duration_to_pt', sa.Integer(), nullable=False, server_default='1800')
    )
    op.add_column('instance', sa.Column('max_nb_transfers', sa.Integer(), nullable=False, server_default='10'))
    op.add_column(
        'instance', sa.Column('max_walking_duration_to_pt', sa.Integer(), nullable=False, server_default='900')
    )
    op.add_column('instance', sa.Column('walking_speed', sa.Float(), nullable=False, server_default='1.12'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic ###
    op.drop_column('instance', 'walking_speed')
    op.drop_column('instance', 'max_walking_duration_to_pt')
    op.drop_column('instance', 'max_nb_transfers')
    op.drop_column('instance', 'max_car_duration_to_pt')
    op.drop_column('instance', 'max_bss_duration_to_pt')
    op.drop_column('instance', 'max_bike_duration_to_pt')
    op.drop_column('instance', 'car_speed')
    op.drop_column('instance', 'bss_speed')
    op.drop_column('instance', 'bike_speed')
    ### end Alembic commands ###
