""" add pt_planners for distributed

Revision ID: 535dfe5be550
Revises: bd4a1dd22029
Create Date: 2022-03-08 14:34:20.841394

"""

# revision identifiers, used by Alembic.
revision = '535dfe5be550'
down_revision = 'bd4a1dd22029'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import json

from navitiacommon import default_values


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'instance',
        sa.Column('pt_planner_id', sa.Text(), server_default=default_values.pt_planner_id, nullable=False),
    )

    op.add_column(
        'instance',
        sa.Column(
            'pt_planners_configurations',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=json.dumps(default_values.pt_planners_configurations),
            nullable=True,
        ),
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'pt_planners_configurations')
    op.drop_column('instance', 'pt_planner_id')
    # ### end Alembic commands ###
