"""add an app_name for the keys

Revision ID: 5423986c3a51
Revises: 1b1bc5bf715a
Create Date: 2014-12-05 15:54:02.680699

"""

# revision identifiers, used by Alembic.
revision = '5423986c3a51'
down_revision = '1b1bc5bf715a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key', sa.Column('app_name', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('key', 'app_name')
    ### end Alembic commands ###
