"""add is_open_data field

Revision ID: 57ee5581cc30
Revises: 5ad2dddab995
Create Date: 2016-11-21 16:50:06.889678

"""

# revision identifiers, used by Alembic.
revision = '57ee5581cc30'
down_revision = '5ad2dddab995'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column('instance', sa.Column('is_open_data', sa.Boolean(), nullable=True))
    op.execute('update instance set is_open_data=is_free')
    op.alter_column('instance', 'is_open_data', nullable=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'is_open_data')
    ### end Alembic commands ###
