"""Add same_journey_schedules_configuration to instance table

Revision ID: 8b3ddc6272b0
Revises: 79bd4783fd9e
Create Date: 2025-03-12 17:44:03.089412
"""

# revision identifiers, used by Alembic.
revision = '8b3ddc6272b0'
down_revision = '79bd4783fd9e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic###
    op.add_column(
        'instance',
        sa.Column(
            'same_journey_schedules_configuration',
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"allowed_id_type": ["stop_point"], "min_nb_journeys": 5}',
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic###
    op.drop_column('instance', 'same_journey_schedules_configuration')
