"""Add language column for Asgard

Revision ID: 8ede48ca4e23
Revises: 7f757939ace8
Create Date: 2021-07-13 15:42:02.597826

"""

# revision identifiers, used by Alembic.
revision = '8ede48ca4e23'
down_revision = '7f757939ace8'

from alembic import op
import sqlalchemy as sa
from navitiacommon import default_values


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'instance',
        sa.Column(
            'asgard_language',
            sa.Text(),
            nullable=False,
            server_default='{}'.format(default_values.asgard_language),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'asgard_language')
    # ### end Alembic commands ###
