"""Add language column for Asgard

Revision ID: c2ae8e936eae
Revises: a053ceeccdd9
Create Date: 2021-08-12 12:18:40.516198

"""

# revision identifiers, used by Alembic.
revision = 'c2ae8e936eae'
down_revision = 'a053ceeccdd9'

from alembic import op
import sqlalchemy as sa
from navitiacommon import default_values


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'instance',
        sa.Column(
            'asgard_language',
            sa.Text(),
            nullable=False,
            server_default='{}'.format(default_values.asgard_language),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'asgard_language')
    # ### end Alembic commands ###
