"""Add table sn_backend_authorization

Revision ID: d4b48ec451ed
Revises: e3e7d4fdee23
Create Date: 2024-03-05 18:02:08.524832

"""

# revision identifiers, used by Alembic.
revision = 'd4b48ec451ed'
down_revision = 'e3e7d4fdee23'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sn_backend_authorization',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('sn_backend_id', sa.Text(), nullable=False),
        sa.Column('mode', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['sn_backend_id'], ['streetnetwork_backend.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('user_id', 'mode'),
    )

    op.add_column('user', sa.Column('has_sn_backend', sa.Boolean(), server_default='False', nullable=False))


def downgrade():
    op.drop_table('sn_backend_authorization')

    op.drop_column('user', 'has_sn_backend')
