"""add use_predicted_traffic

Revision ID: fd13bb348665
Revises: d7ff7aea17d9
Create Date: 2024-10-10 15:14:54.523574

"""

# revision identifiers, used by Alembic.
revision = 'fd13bb348665'
down_revision = 'd7ff7aea17d9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'instance', sa.Column('use_predicted_traffic', sa.Boolean(), server_default='False', nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'use_predicted_traffic')
    # ### end Alembic commands ###
