from v0 import Regions, Ptref, Places, PlacesNearby, Journeys, TimeTables
def v0_routing(api):
    api.add_resource(Regions.Regions,
                     '/v0/regions.json',
                     endpoint='v0.regions')
    api.add_resource(Ptref.StopAreas,
                     '/v0/<string:region>/stop_areas.json',
                     endpoint='v0.stop_areas')
    api.add_resource(Ptref.StopPoints,
                     '/v0/<string:region>/stop_points.json',
                     endpoint='v0.stop_points')
    api.add_resource(Ptref.Lines,
                     '/v0/<string:region>/lines.json',
                     endpoint='v0.lines')
    api.add_resource(Ptref.Routes,
                     '/v0/<string:region>/routes.json',
                     endpoint='v0.routes')
    api.add_resource(Ptref.PhysicalModes,
                     '/v0/<string:region>/physical_modes.json',
                     endpoint='v0.physical_modes')
    api.add_resource(Ptref.CommercialModes,
                     '/v0/<string:region>/commercial_modes.json',
                     endpoint='v0.commercial_modes')
    api.add_resource(Ptref.Connections,
                     '/v0/<string:region>/connections.json',
                     endpoint='v0.connections')
    api.add_resource(Ptref.JourneyPatternPoints,
                     '/v0/<string:region>/journey_pattern_points.json',
                     endpoint='v0.Journey_pattern_points')
    api.add_resource(Ptref.JourneyPatterns,
                     '/v0/<string:region>/journey_patterns.json',
                     endpoint='v0.journey_patterns')
    api.add_resource(Ptref.Companies,
                     '/v0/<string:region>/companies.json',
                     endpoint='v0.companies')
    api.add_resource(Ptref.VehicleJourneys,
                     '/v0/<string:region>/vehicle_journeys.json',
                     endpoint='v0.vehicle_journeys')
    api.add_resource(Ptref.Pois,
                     '/v0/<string:region>/pois.json',
                     endpoint='v0.pois')
    api.add_resource(Ptref.PoiTypes,
                     '/v0/<string:region>/poi_types.json',
                     endpoint='v0.poi_types')
    api.add_resource(Places.Places,
                     '/v0/<string:region>/places.json',
                     endpoint='v0.places')
    api.add_resource(PlacesNearby.PlacesNearby,
                     '/v0/<string:region>/places_nearby.json',
                     endpoint='v0.places_nearby')
    api.add_resource(Journeys.Journeys,
                     '/v0/<string:region>/journeys.json',
                     endpoint='v0.journeys')
    api.add_resource(Journeys.Isochrone,
                     '/v0/<string:region>/isochrone.json',
                     endpoint='v0.isochrone')
    api.add_resource(TimeTables.NextDepartures,
                     '/v0/<string:region>/next_departures.json',
                     endpoint='v0.next_departures')
    api.add_resource(TimeTables.NextArrivals,
                     '/v0/<string:region>/next_arrivals.json',
                     endpoint='v0.next_arrivals')
    api.add_resource(TimeTables.DepartureBoards,
                     '/v0/<string:region>/departure_boards.json',
                     endpoint='v0.departure_boards')
    api.add_resource(TimeTables.RouteSchedules,
                     '/v0/<string:region>/route_schedules.json',
                     endpoint='v0.route_schedules')
    api.add_resource(TimeTables.StopsSchedules,
                     '/v0/<string:region>/stops_schedules.json',
                     endpoint='v0.stops_schedules')

