FROM debian:bullseye-slim

WORKDIR /usr/share/tyr/

COPY ./docker/ca-certificates/*.crt /usr/local/share/ca-certificates/
COPY ./source/sql/requirements.txt /tmp/requirements.txt
RUN apt clean \
    && apt update --fix-missing \
    && apt install -o Acquire::Retries=10 -y libgeos-dev libpq5 python3.9-dev python3-pip git ca-certificates postgresql-client gettext-base jq \
    && update-ca-certificates \
    && pip3 install --no-cache-dir -U uv \ 
    && uv pip install --system -r /tmp/requirements.txt

COPY ./source/navitiacommon ./navitiacommon
COPY ./source/tyr ./tyr
RUN (cd navitiacommon && python3 setup.py install) \
    && (cd tyr && python3 setup.py install && uv pip install --system --no-cache-dir -U -r requirements.txt)

COPY ./source/sql/alembic /usr/share/navitia/ed/alembic
COPY ./source/cities /usr/share/navitia/cities
COPY ./docker/templates/* /templates/
COPY --chmod=755 ./docker/run_tyr_beat.sh /run_tyr_beat.sh

RUN apt purge -y git \
    && apt autoremove -y

ENTRYPOINT ["bash", "/run_tyr_beat.sh"]
