FIND_PATH(FCGI_INCLUDE_DIR fcgiapp.h)

FIND_LIBRARY(FCGI_LIBRARY NAMES fcgi) 

IF (FCGI_INCLUDE_DIR AND FCGI_LIBRARY)
   SET(FCGI_FOUND TRUE)
ENDIF (FCGI_INCLUDE_DIR AND FCGI_LIBRARY)


IF (FCGI_FOUND)
   IF (NOT Fcgi_FIND_QUIETLY)
      MESSAGE(STATUS "Found Fcgi: ${FCGI_LIBRARY}")
   ENDIF (NOT Fcgi_FIND_QUIETLY)
ELSE (FCGI_FOUND)
   IF (Fcgi_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Fcgi")
   ENDIF (Fcgi_FIND_REQUIRED)
ENDIF (FCGI_FOUND)

