FIND_PATH(RAPIDXML_INCLUDE_DIR rapidxml.hpp PATH "${CMAKE_SOURCE_DIR}/third_party/rapidxml/")

IF (RAPIDXML_INCLUDE_DIR)
      MESSAGE(STATUS "Found rapidxml: ${RAPIDXML_INCLUDE_DIR}")
ELSE (RAPIDXML_FOUND)
   IF (RAPIDXML_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find rapidxml")
   ENDIF (RAPIDXML_FIND_REQUIRED)
ENDIF (RAPIDXML_INCLUDE_DIR)

