#!/bin/sh
case "$1" in
    configure)
        chmod +x /usr/share/kraken/
        chmod +x /usr/share/kraken/scripts/
        chmod +x /usr/share/kraken/scripts/navimake_updater.sh
        chmod +x /usr/share/kraken/scripts/update_data.sh
        chmod +x /usr/share/ed/
        chmod +x /usr/share/ed/scripts/
        chmod +x /usr/share/ed/scripts/update_db.sh
        chmod +x /usr/share/ed/scripts/init_db.sh
        chmod +r -R /usr/share/kraken/
        chmod +r -R /usr/share/ed/
        chmod +rx -R /srv/jormungandr/
        chmod +x /srv/jormungandr/jormungandr.py
        chmod +x /usr/bin/pyed_service.py
        chmod +x /usr/bin/gtfs2ed
        chmod +x /usr/bin/osm2ed
        chmod +x /usr/bin/ed2nav
        chmod +x /usr/bin/kraken
        chown root:www-data /usr/share/kraken/scripts/navimake_updater.sh
        chown root:www-data /usr/share/kraken/scripts/update_data.sh
        chown root:www-data /usr/share/ed/scripts/update_db.sh
        chown root:www-data /usr/share/ed/scripts/init_db.sh
        cd /tmp/;python /tmp/setup.py install
        rm -R /tmp/pyed
        rm /tmp/setup.py
        ;;
esac
