#!/bin/sh
case "$1" in
    configure)
        chmod +x /usr/share/kraken/
        chmod +x /usr/share/kraken/scripts/
        chmod +x /usr/share/kraken/scripts/{init, update}_db.sh
        chmod +r -R /usr/share/kraken/
        chmod +rx -R /srv/jormungandr/
        chown root:www-data /usr/share/kraken/scripts/{init, update}_db.sh
        chmod +x /tmp/setup.py
        python /tmp/setup.py install
        rm -R /tmp/pyed
        rm /tmp/setup.py 
        ;;
esac
