FROM python:3.11-slim-bookworm

WORKDIR /usr/share/tyr/

COPY ./source/navitiacommon ./navitiacommon
COPY ./source/navitia-proto ./navitia-proto
COPY ./source/tyr ./tyr
COPY ./docker/ca-certificates/*.crt /usr/local/share/ca-certificates/
COPY ./docker/run_tyr_beat.sh /run_tyr_beat.sh
COPY ./source/sql/alembic /usr/share/navitia/ed/alembic
COPY ./source/sql/requirements.txt /tmp/requirements.txt
COPY ./source/cities /usr/share/navitia/cities
COPY ./docker/templates/* /templates/
RUN chmod +x /run_tyr_beat.sh

RUN apt clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt update --fix-missing \
    && apt-get upgrade -y \
    && apt install -o Acquire::Retries=10 -y curl libgeos-dev libpq5 git ca-certificates postgresql-client gettext-base jq gcc \
    && update-ca-certificates \
    && curl -fsSL -o /tmp/protoc-python.zip https://github.com/protocolbuffers/protobuf/releases/download/v29.5/protoc-29.5-linux-x86_64.zip \
    && python3 -m zipfile -e /tmp/protoc-python.zip /tmp/protoc-python && install -Dm0755 /tmp/protoc-python/bin/protoc /usr/local/bin/protoc-python \
    && (cd navitia-proto && protoc-python --python_out=../navitiacommon/navitiacommon type.proto response.proto request.proto task.proto stat.proto) \
    && 2to3 --no-diffs -w navitiacommon/navitiacommon/*_pb2.py \
    && (cd navitiacommon && python setup.py install) \
    && (cd tyr && python setup.py install && pip install --no-cache-dir -U -r requirements.txt)\
    && pip install --no-cache-dir -U -r /tmp/requirements.txt \
    && rm -rf navitiacommon navitia-proto /usr/local/bin/protoc-python \
    && apt purge -y git \
    && apt autoremove -y

ENTRYPOINT ["bash", "/run_tyr_beat.sh"]
