#pragma once

#define FIXTURES_DIR "${FIXTURES_DIR}"
#cmakedefine HAVE_ICONV_H 1

#cmakedefine HAVE_LOGGINGMACROS_H 1

#define NAVITIA_BUILD_TYPE "${CMAKE_BUILD_TYPE}"

#define KRAKEN_VERSION "${GIT_REVISION}"
