#pragma once

#define FIXTURES_DIR "${FIXTURES_DIR}"
#cmakedefine HAVE_ICONV_H 1

#cmakedefine HAVE_LOGGINGMACROS_H 1

#define NAVITIA_VERSION_MAJOR "${NAVITIA_VERSION_MAJOR}"
#define NAVITIA_VERSION_MINOR "${NAVITIA_VERSION_MINOR}"
#define NAVITIA_VERSION_PATCH "${NAVITIA_VERSION_PATCH}"
#define NAVITIA_BUILD_TYPE "${CMAKE_BUILD_TYPE}"

#define NAVITIA_VERSION "${NAVITIA_VERSION_MAJOR}.${NAVITIA_VERSION_MINOR}.${NAVITIA_VERSION_PATCH}"
