name: SonarCloud

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  static_analysis:
    runs-on: [self-hosted, corefront, sandbox]
    container:
        image: debian:bullseye

    steps:
    - name: Install git
      run: |
        apt clean
        apt update --fix-missing
        apt install -o Acquire::Retries=10 git -y

    - name: Install sonar dependencies
      run: apt install -y unzip

    - name: force chown to avoid errors
      run: chown -R $(whoami):$(whoami) .

    - name: Generate github private access token
      id: ci-core-app-token
      uses: getsentry/action-github-app-token@v2.0.0
      with:
        app_id: ${{ secrets.CI_CORE_APP_ID }}
        private_key: ${{ secrets.CI_CORE_APP_PEM }}
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ steps.ci-core-app-token.outputs.token }}

    - name: install dependencies
      run: ./scripts/navitia_dependencies.sh

    - name: Configure
      run: |
        mkdir build
        cmake -DCMAKE_BUILD_TYPE=Profile -DSTRIP_SYMBOLS=ON -S source -B build

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.3.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          args: >
            --define sonar.cfamily.compile-commands=build/compile_commands.json

    - name: clean up workspace
      if: ${{ always() }}
      run: |
        rm -rf ./*
        rm -rf ./.??*

